const API = 'https://ecommerce-backend-ss1r.onrender.com/api/v1';

function imgs(slug: string, count = 7) {
  return Array.from({ length: count }, (_, i) => ({
    url: `https://picsum.photos/seed/${slug}-${i + 1}/600/800`,
    alt: `${slug} image ${i + 1}`,
    isPrimary: i === 0,
    displayOrder: i,
  }));
}

function variants(sku: string, sizes: string[], colors: { name: string; hex: string }[], price: number) {
  const v: any[] = [];
  for (const c of colors) {
    for (const s of sizes) {
      v.push({ size: s, color: c.name, colorHex: c.hex, sku: `${sku}-${c.name.toUpperCase().slice(0, 3)}-${s}`, price, stock: Math.floor(Math.random() * 40) + 5 });
    }
  }
  return v;
}

const MEN_SIZES = ['S', 'M', 'L', 'XL', 'XXL'];
const WOMEN_SIZES = ['XS', 'S', 'M', 'L', 'XL'];
const KID_SIZES = ['4-5Y', '6-7Y', '8-9Y', '10-11Y', '12-13Y'];
const SHOE_SIZES = ['6', '7', '8', '9', '10'];

const B = { name: 'Black', hex: '#000000' };
const W = { name: 'White', hex: '#FFFFFF' };
const N = { name: 'Navy', hex: '#1a1a2e' };
const R = { name: 'Red', hex: '#e94560' };
const BL = { name: 'Blue', hex: '#2563eb' };
const G = { name: 'Green', hex: '#16a34a' };
const GR = { name: 'Grey', hex: '#6b7280' };
const MR = { name: 'Maroon', hex: '#7f1d1d' };
const BG = { name: 'Beige', hex: '#d4a853' };
const PK = { name: 'Pink', hex: '#ec4899' };
const LV = { name: 'Lavender', hex: '#c084fc' };
const OL = { name: 'Olive', hex: '#65a30d' };
const BR = { name: 'Brown', hex: '#92400e' };
const TN = { name: 'Tan', hex: '#d2a679' };
const GL = { name: 'Gold', hex: '#d4a853' };
const SV = { name: 'Silver', hex: '#c0c0c0' };
const YL = { name: 'Yellow', hex: '#eab308' };
const DB = { name: 'Dark Blue', hex: '#1e3a5f' };
const DG = { name: 'Dark Grey', hex: '#374151' };
const LB = { name: 'Light Blue', hex: '#93c5fd' };
const KHAKI = { name: 'Khaki', hex: '#c3b091' };

interface P {
  name: string;
  desc: string;
  short: string;
  tags: string;
  gender: string;
  base: number;
  sale: number;
  sku: string;
  catSlug: string;
  brandSlug: string;
  fabric: string;
  material: string;
  wash: string;
  feat: boolean;
  newArr: boolean;
  best: boolean;
  trend: boolean;
  flash: boolean;
  fest: boolean;
  sizes: string[];
  colors: any[];
  imgCount: number;
}

const products: P[] = [
  // ===== MEN T-SHIRTS (10) =====
  { name: 'Classic Crew Neck T-Shirt', desc: 'A wardrobe essential crafted from 100% combed cotton. This crew neck t-shirt features a regular fit with pre-shrunk fabric that retains its shape wash after wash. Ribbed collar maintains its form, while double-stitched seams ensure durability. The soft hand feel makes it perfect for all-day wear.', short: 'Premium cotton crew neck with regular fit', tags: 't-shirt,cotton,casual,basics,crew-neck', gender: 'MEN', base: 799, sale: 499, sku: 'M-TS-101', catSlug: 'men-t-shirts', brandSlug: 'premium-wear', fabric: '100% Combed Cotton', material: 'Pure Cotton 180 GSM', wash: 'Machine wash cold. Do not bleach.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, W, N, GR], imgCount: 7 },
  { name: 'Slim Fit Polo T-Shirt', desc: 'Smart-casual polo shirt in premium pique cotton with a tailored slim fit. Features a classic two-button placket, ribbed collar and cuffs. Perfect for weekend brunches, golf outings, or casual office days.', short: 'Pique cotton polo with slim fit', tags: 'polo,t-shirt,cotton,smart-casual,slim-fit', gender: 'MEN', base: 1299, sale: 899, sku: 'M-TS-102', catSlug: 'men-t-shirts', brandSlug: 'urban-style', fabric: 'Pique Cotton', material: 'Cotton Blend 200 GSM', wash: 'Machine wash inside out.', feat: true, newArr: false, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, W, N, R], imgCount: 7 },
  { name: 'Oversized Graphic Tee', desc: 'Streetwear-inspired oversized t-shirt with bold graphic print. Made from heavyweight 220 GSM cotton with a dropped shoulder silhouette. Pairs perfectly with cargo pants, joggers, or slim jeans.', short: 'Heavyweight oversized graphic tee', tags: 'graphic-tee,oversized,streetwear,cotton', gender: 'MEN', base: 1499, sale: 999, sku: 'M-TS-103', catSlug: 'men-t-shirts', brandSlug: 'street-vogue', fabric: 'Heavyweight Cotton', material: '100% Cotton 220 GSM', wash: 'Turn inside out before washing.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, W, GR], imgCount: 7 },
  { name: 'Henley Neck T-Shirt', desc: 'Versatile henley neck t-shirt with a three-button placket. Made from soft cotton jersey with a relaxed fit. The henley collar adds a touch of rugged sophistication.', short: 'Cotton henley with button placket', tags: 'henley,t-shirt,cotton,layering', gender: 'MEN', base: 999, sale: 699, sku: 'M-TS-104', catSlug: 'men-t-shirts', brandSlug: 'classic-threads', fabric: 'Cotton Jersey', material: '100% Cotton 180 GSM', wash: 'Machine wash cold.', feat: false, newArr: false, best: true, trend: false, flash: true, fest: false, sizes: MEN_SIZES, colors: [B, N, MR, GR], imgCount: 7 },
  { name: 'V-Neck Solid T-Shirt', desc: 'Elegant v-neck t-shirt in smooth cotton jersey. The deeper V-neckline creates a flattering silhouette while the slim-fit cut accentuates the body.', short: 'Slim fit v-neck in premium cotton', tags: 'v-neck,t-shirt,cotton,slim-fit', gender: 'MEN', base: 899, sale: 599, sku: 'M-TS-105', catSlug: 'men-t-shirts', brandSlug: 'modern-fit', fabric: 'Cotton Elastane', material: '95% Cotton, 5% Elastane', wash: 'Machine wash cold with similar colors.', feat: false, newArr: false, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, W, N], imgCount: 7 },
  { name: 'Performance Dry-Fit T-Shirt', desc: 'Engineered for active lifestyles with moisture-wicking technology. Lightweight and breathable with mesh ventilation panels. Four-way stretch for unrestricted movement.', short: 'Moisture-wicking sports tee', tags: 'activewear,sports,dry-fit,gym,running', gender: 'MEN', base: 1199, sale: 799, sku: 'M-TS-108', catSlug: 'men-t-shirts', brandSlug: 'elite-collection', fabric: 'Polyester Spandex', material: '92% Polyester, 8% Spandex', wash: 'Machine wash cold. No fabric softener.', feat: false, newArr: false, best: true, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, N, R, G], imgCount: 7 },
  { name: 'Linen Blend Vacation Tee', desc: 'Relaxed-fit t-shirt in a breathable linen-cotton blend. The natural texture gives it a laid-back vacation vibe while cotton ensures softness.', short: 'Linen blend relaxed tee', tags: 'linen,summer,vacation,casual,blend', gender: 'MEN', base: 1299, sale: 899, sku: 'M-TS-109', catSlug: 'men-t-shirts', brandSlug: 'classic-threads', fabric: 'Linen Cotton Blend', material: '55% Linen, 45% Cotton', wash: 'Hand wash recommended.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [W, BG, N], imgCount: 7 },
  { name: 'Longline T-Shirt', desc: 'Contemporary longline t-shirt with an extended hem and side slits. Made from premium cotton with a relaxed drape for a modern streetwear aesthetic.', short: 'Extended hem longline tee', tags: 'longline,t-shirt,streetwear,modern', gender: 'MEN', base: 1099, sale: 799, sku: 'M-TS-107', catSlug: 'men-t-shirts', brandSlug: 'street-vogue', fabric: 'Cotton', material: '100% Cotton 190 GSM', wash: 'Machine wash cold. Hang dry.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, W, GR], imgCount: 7 },
  { name: 'Striped Rugby T-Shirt', desc: 'Classic rugby-style t-shirt with bold horizontal stripes and reinforced collar. Made from durable cotton jersey with contrast tape at the placket.', short: 'Rugby style striped t-shirt', tags: 'rugby,striped,t-shirt,casual,vintage', gender: 'MEN', base: 1399, sale: 999, sku: 'M-TS-106', catSlug: 'men-t-shirts', brandSlug: 'premium-wear', fabric: 'Cotton Jersey', material: '100% Cotton 200 GSM', wash: 'Machine wash cold. Wash inside out.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: true, sizes: MEN_SIZES, colors: [N, R, G], imgCount: 7 },
  { name: 'Zip-Up Hoodie T-Shirt', desc: 'Hybrid zip-up t-shirt with lightweight terry fabric and full-zip front. Features raglan sleeves for enhanced mobility and a stand collar.', short: 'Lightweight zip-up terry top', tags: 'zip-up,hoodie,layering,terry', gender: 'MEN', base: 1599, sale: 1099, sku: 'M-TS-110', catSlug: 'men-t-shirts', brandSlug: 'urban-style', fabric: 'French Terry', material: '80% Cotton, 20% Polyester', wash: 'Machine wash cold. Zip before washing.', feat: false, newArr: false, best: false, trend: false, flash: true, fest: false, sizes: MEN_SIZES, colors: [B, GR, N], imgCount: 7 },

  // ===== MEN SHIRTS (8) =====
  { name: 'Classic Oxford Button-Down', desc: 'Timeless Oxford cloth button-down shirt with a tailored fit. Features a button-down collar, single chest pocket, and adjustable barrel cuffs. The Oxford weave provides subtle texture that bridges casual and smart.', short: 'Oxford cotton button-down shirt', tags: 'shirt,oxford,cotton,formal,smart-casual', gender: 'MEN', base: 2299, sale: 1599, sku: 'M-SH-201', catSlug: 'men-shirts', brandSlug: 'classic-threads', fabric: 'Oxford Cotton', material: '100% Cotton 140 GSM', wash: 'Machine wash warm. Iron while damp.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [W, BL, N, PK], imgCount: 8 },
  { name: 'Slim Fit Linen Shirt', desc: 'Breathable linen shirt with a modern slim fit. Features a spread collar, front patch pocket, and mitered cuffs. Ideal for summer weddings and garden parties.', short: 'Slim fit linen shirt for summer', tags: 'linen,shirt,summer,slim-fit,formal', gender: 'MEN', base: 2799, sale: 1999, sku: 'M-SH-202', catSlug: 'men-shirts', brandSlug: 'premium-wear', fabric: '100% Linen', material: 'Pure Linen 150 GSM', wash: 'Hand wash cold. Hang dry.', feat: true, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [W, BG, LB, G], imgCount: 7 },
  { name: 'Flannel Check Shirt', desc: 'Warm and cozy flannel shirt in a classic plaid pattern. Made from brushed cotton flannel that gets softer with each wash. A perfect layering piece for fall and winter.', short: 'Brushed flannel plaid shirt', tags: 'flannel,check,winter,casual,plaid', gender: 'MEN', base: 2499, sale: 1799, sku: 'M-SH-203', catSlug: 'men-shirts', brandSlug: 'urban-style', fabric: 'Brushed Flannel', material: '100% Cotton Flannel 160 GSM', wash: 'Machine wash warm with like colors.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: true, sizes: MEN_SIZES, colors: [R, N, G, GR], imgCount: 7 },
  { name: 'Formal Spread Collar Shirt', desc: 'Impeccably tailored formal shirt in premium cotton poplin. Features a wide spread collar, French placket, and adjustable cuff links. Wrinkle-resistant finish.', short: 'Premium cotton formal shirt', tags: 'formal,shirt,cotton,office,tie', gender: 'MEN', base: 2999, sale: 2199, sku: 'M-SH-204', catSlug: 'men-shirts', brandSlug: 'elite-collection', fabric: 'Cotton Poplin', material: '100% Egyptian Cotton', wash: 'Dry clean recommended.', feat: true, newArr: false, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [W, BL, PK, LV], imgCount: 7 },
  { name: 'Denim Western Shirt', desc: 'Rugged denim shirt with authentic Western detailing. Snap-button front, twin chest pockets, and curved hem. Made from soft washed denim.', short: 'Western style denim shirt', tags: 'denim,western,shirt,casual,rugged', gender: 'MEN', base: 2699, sale: 1899, sku: 'M-SH-205', catSlug: 'men-shirts', brandSlug: 'street-vogue', fabric: 'Denim', material: '100% Cotton Denim 12oz', wash: 'Wash inside out in cold water.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [BL, B, GR], imgCount: 7 },
  { name: 'Camp Collar Resort Shirt', desc: 'Relaxed camp collar shirt inspired by vintage resort wear. Open collar, boxy fit, and tropical print on lightweight viscose.', short: 'Camp collar resort shirt', tags: 'camp-collar,resort,summer,vacation,printed', gender: 'MEN', base: 1899, sale: 1399, sku: 'M-SH-206', catSlug: 'men-shirts', brandSlug: 'modern-fit', fabric: 'Viscose', material: '100% Viscose', wash: 'Hand wash cold.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [G, BL, BG], imgCount: 7 },
  { name: 'Striped Regular Fit Shirt', desc: 'Classic striped shirt with a comfortable regular fit. Straight collar, full button front, single chest pocket. Timeless vertical stripes create a slimming effect.', short: 'Regular fit striped cotton shirt', tags: 'striped,shirt,cotton,regular-fit', gender: 'MEN', base: 1999, sale: 1399, sku: 'M-SH-207', catSlug: 'men-shirts', brandSlug: 'classic-threads', fabric: 'Cotton Blend', material: '80% Cotton, 20% Polyester', wash: 'Machine wash cold.', feat: false, newArr: false, best: true, trend: false, flash: true, fest: false, sizes: MEN_SIZES, colors: [W, BL, N], imgCount: 7 },
  { name: 'Corduroy Overshirt', desc: 'Heavyweight corduroy overshirt bridging shirt and jacket. Spread collar, button front, chest pockets. Rich corduroy texture adds depth and warmth.', short: 'Corduroy overshirt layering piece', tags: 'corduroy,overshirt,layering,autumn,winter', gender: 'MEN', base: 3499, sale: 2499, sku: 'M-SH-208', catSlug: 'men-shirts', brandSlug: 'elite-collection', fabric: 'Corduroy', material: '100% Cotton Corduroy', wash: 'Machine wash cold inside out.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [N, BR, G], imgCount: 7 },

  // ===== MEN JEANS (7) =====
  { name: 'Slim Fit Stretch Jeans', desc: 'Modern slim fit jeans with 4-way stretch denim. Mid-rise waist, tapered leg. Classic five-pocket styling with reinforced rivets. Advanced stretch recovery ensures shape retention.', short: '4-way stretch slim fit jeans', tags: 'jeans,slim-fit,stretch,denim', gender: 'MEN', base: 2999, sale: 1999, sku: 'M-JN-301', catSlug: 'men-jeans', brandSlug: 'modern-fit', fabric: 'Stretch Denim', material: '98% Cotton, 2% Elastane', wash: 'Machine wash cold inside out.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [BL, B, GR], imgCount: 7 },
  { name: 'Regular Fit Classic Indigo', desc: 'Timeless regular fit jeans in authentic indigo wash. Made from 12oz rigid denim that develops a unique patina over time. Straight leg with comfortable mid-rise.', short: 'Classic indigo regular fit jeans', tags: 'jeans,regular-fit,indigo,classic,rigid', gender: 'MEN', base: 2499, sale: 1799, sku: 'M-JN-302', catSlug: 'men-jeans', brandSlug: 'classic-threads', fabric: 'Rigid Denim', material: '100% Cotton Denim 12oz', wash: 'Wash sparingly. Cold water only.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [BL, DB], imgCount: 7 },
  { name: 'Skinny Fit Black Jeans', desc: 'Sleek skinny fit jeans in jet-black wash. Super-stretch fabric for a body-hugging fit. Low-rise waist with ankle-length hem.', short: 'Jet black skinny jeans', tags: 'jeans,skinny,black,stretch', gender: 'MEN', base: 2799, sale: 1899, sku: 'M-JN-303', catSlug: 'men-jeans', brandSlug: 'street-vogue', fabric: 'Stretch Denim', material: '97% Cotton, 3% Elastane', wash: 'Wash inside out in cold water.', feat: false, newArr: false, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, DG], imgCount: 7 },
  { name: 'Relaxed Fit Cargo Jeans', desc: 'Utilitarian cargo jeans with relaxed fit. Side cargo pockets with button flaps, back welt pockets, and tapered leg. Blends workwear heritage with modern streetwear.', short: 'Cargo style relaxed fit jeans', tags: 'cargo,jeans,relaxed,utility,streetwear', gender: 'MEN', base: 3299, sale: 2299, sku: 'M-JN-304', catSlug: 'men-jeans', brandSlug: 'street-vogue', fabric: 'Cotton Twill', material: '100% Cotton', wash: 'Machine wash cold with like colors.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [G, B, BG], imgCount: 7 },
  { name: 'Tapered Fit Acid Wash Jeans', desc: 'Statement acid wash jeans with modern tapered fit. Mid-rise waist, five-pocket styling, tapered leg. Bold acid wash pattern creates a retro 80s vibe.', short: 'Acid wash tapered jeans', tags: 'jeans,tapered,acid-wash,retro', gender: 'MEN', base: 2699, sale: 1899, sku: 'M-JN-305', catSlug: 'men-jeans', brandSlug: 'urban-style', fabric: 'Denim', material: '100% Cotton Denim', wash: 'Wash inside out. Cold water.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [BL, B], imgCount: 7 },
  { name: 'High Rise Straight Jeans', desc: 'Vintage-inspired high rise jeans with straight leg. Non-stretch rigid denim for authentic retro feel. Button fly, copper rivets, raw hem.', short: 'High rise straight leg jeans', tags: 'jeans,high-rise,straight,vintage,rigid', gender: 'MEN', base: 2899, sale: 2099, sku: 'M-JN-306', catSlug: 'men-jeans', brandSlug: 'premium-wear', fabric: 'Rigid Denim', material: '100% Cotton Denim 14oz', wash: 'Dry clean preferred.', feat: false, newArr: false, best: false, trend: false, flash: true, fest: false, sizes: MEN_SIZES, colors: [BL, B], imgCount: 7 },
  { name: 'Distressed Boyfriend Jeans', desc: 'Relaxed boyfriend jeans with intentional distressing. Low-to-mid rise, relaxed through hip and thigh, tapered leg. Pre-worn look gives instant character.', short: 'Distressed boyfriend fit jeans', tags: 'jeans,boyfriend,distressed,ripped,casual', gender: 'MEN', base: 2599, sale: 1799, sku: 'M-JN-307', catSlug: 'men-jeans', brandSlug: 'urban-style', fabric: 'Denim', material: '99% Cotton, 1% Elastane', wash: 'Machine wash cold.', feat: false, newArr: false, best: false, trend: true, flash: false, fest: true, sizes: MEN_SIZES, colors: [BL, LB, B], imgCount: 7 },

  // ===== MEN JACKETS (7) =====
  { name: 'Classic Bomber Jacket', desc: 'Iconic bomber jacket with lightweight quilted lining. Zip front, rib-knit collar/cuffs/hem, slanted side pockets. Water-resistant shell for practical everyday wear.', short: 'Quilted bomber with zip closure', tags: 'bomber,jacket,outerwear,casual,classic', gender: 'MEN', base: 4999, sale: 3499, sku: 'M-JK-401', catSlug: 'men-jackets', brandSlug: 'premium-wear', fabric: 'Nylon Polyester', material: '100% Polyester Shell', wash: 'Machine wash cold on gentle.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, N, OL], imgCount: 7 },
  { name: 'Premium Leather Biker Jacket', desc: 'Luxurious genuine leather biker jacket with asymmetric zip closure. Notch lapels with silver snap buttons, quilted shoulder panels, multiple zip pockets. Fully lined in satin.', short: 'Genuine leather biker jacket', tags: 'leather,biker,jacket,premium,luxury', gender: 'MEN', base: 14999, sale: 10999, sku: 'M-JK-402', catSlug: 'men-jackets', brandSlug: 'elite-collection', fabric: 'Genuine Leather', material: '100% Sheep Leather', wash: 'Professional leather clean only.', feat: true, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, BR], imgCount: 8 },
  { name: 'Denim Trucker Jacket', desc: 'Classic trucker jacket in medium-wash denim. Button front, chest pockets with button flaps, adjustable waist tabs. Versatile mid-weight denim layering piece.', short: 'Classic denim trucker jacket', tags: 'denim,trucker,jacket,classic,layering', gender: 'MEN', base: 3999, sale: 2799, sku: 'M-JK-403', catSlug: 'men-jackets', brandSlug: 'classic-threads', fabric: 'Denim', material: '100% Cotton Denim', wash: 'Wash inside out in cold water.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: true, sizes: MEN_SIZES, colors: [BL, B], imgCount: 7 },
  { name: 'Puffer Jacket - Winter Edition', desc: 'Insulated puffer jacket with responsibly sourced down fill. Water-resistant shell, zip front with storm flap, elasticated cuffs. Packs down into its own pocket.', short: 'Insulated down puffer jacket', tags: 'puffer,jacket,winter,down,insulated', gender: 'MEN', base: 5999, sale: 4199, sku: 'M-JK-404', catSlug: 'men-jackets', brandSlug: 'elite-collection', fabric: 'Recycled Nylon', material: '100% Recycled Nylon, 700-fill Down', wash: 'Machine wash cold gentle. Tumble dry low.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, N, OL], imgCount: 7 },
  { name: 'Windbreaker Rain Jacket', desc: 'Lightweight packable windbreaker with sealed seams for waterproof protection. Hood, ventilation back panel, reflective details. Weighs under 300g.', short: 'Packable waterproof windbreaker', tags: 'windbreaker,rain,waterproof,lightweight,travel', gender: 'MEN', base: 3499, sale: 2499, sku: 'M-JK-405', catSlug: 'men-jackets', brandSlug: 'urban-style', fabric: 'Ripstop Nylon', material: '100% Nylon with DWR coating', wash: 'Machine wash cold.', feat: false, newArr: false, best: false, trend: false, flash: true, fest: false, sizes: MEN_SIZES, colors: [B, BL, R], imgCount: 7 },
  { name: 'Varsity Baseball Jacket', desc: 'Collegiate-inspired varsity jacket with wool-blend body and faux leather sleeves. Rib-knit collar/cuffs/hem, snap-button closure. Embroidered patches add authentic detailing.', short: 'Varsity baseball jacket', tags: 'varsity,baseball,jacket,collegiate,retro', gender: 'MEN', base: 4499, sale: 3199, sku: 'M-JK-406', catSlug: 'men-jackets', brandSlug: 'street-vogue', fabric: 'Wool Blend', material: '80% Wool, 20% Polyester', wash: 'Dry clean only.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [N, B, G], imgCount: 7 },
  { name: 'Cotton Zip-Up Sweatshirt', desc: 'Minimalist cotton sweatshirt with full-zip front. Brushed fleece cotton with stand collar and ribbed cuffs. Versatile mid-layer for cool evenings.', short: 'Cotton fleece zip-up sweatshirt', tags: 'sweatshirt,zip-up,cotton,fleece,layering', gender: 'MEN', base: 2999, sale: 2099, sku: 'M-JK-407', catSlug: 'men-jackets', brandSlug: 'modern-fit', fabric: 'Brushed Fleece', material: '80% Cotton, 20% Polyester', wash: 'Machine wash cold.', feat: false, newArr: false, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [GR, B, N], imgCount: 7 },

  // ===== MEN HOODIES (5) =====
  { name: 'Classic Pullover Hoodie', desc: 'Essential pullover hoodie in premium cotton fleece. Kangaroo pocket, drawstring hood, ribbed cuffs and hem. Brushed interior provides exceptional warmth.', short: 'Premium cotton pullover hoodie', tags: 'hoodie,pullover,cotton,comfort,casual', gender: 'MEN', base: 2499, sale: 1699, sku: 'M-HD-501', catSlug: 'men-hoodies', brandSlug: 'premium-wear', fabric: 'Cotton Fleece', material: '80% Cotton, 20% Polyester 320 GSM', wash: 'Machine wash cold inside out.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, GR, N, MR], imgCount: 7 },
  { name: 'Oversized Drop-Shoulder Hoodie', desc: 'Trendy oversized hoodie with dropped shoulder seam and extended body length. Heavyweight French terry for structured drape. Double-lined hood and kangaroo pocket.', short: 'Oversized hoodie with drop shoulders', tags: 'hoodie,oversized,streetwear,french-terry', gender: 'MEN', base: 2999, sale: 2099, sku: 'M-HD-502', catSlug: 'men-hoodies', brandSlug: 'street-vogue', fabric: 'French Terry', material: '100% Cotton 380 GSM', wash: 'Machine wash cold.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, W, GR, OL], imgCount: 7 },
  { name: 'Zip-Through Tech Hoodie', desc: 'Performance hoodie with full-zip front and technical fabric. Moisture-wicking, quick-dry technology, zippered side pockets. Streamlined design for workouts and casual.', short: 'Tech fabric zip-up hoodie', tags: 'hoodie,tech,zip-through,performance', gender: 'MEN', base: 3499, sale: 2499, sku: 'M-HD-503', catSlug: 'men-hoodies', brandSlug: 'elite-collection', fabric: 'Tech Fleece', material: '100% Polyester', wash: 'Machine wash cold.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, N, GR], imgCount: 7 },
  { name: 'Colorblock Stripe Hoodie', desc: 'Bold colorblock hoodie with contrasting stripes and panels. Medium-weight cotton fleece with relaxed fit. Graphic front print, kangaroo pocket.', short: 'Colorblock striped hoodie', tags: 'hoodie,colorblock,striped,streetwear', gender: 'MEN', base: 2799, sale: 1999, sku: 'M-HD-504', catSlug: 'men-hoodies', brandSlug: 'street-vogue', fabric: 'Cotton Fleece', material: '80% Cotton, 20% Polyester', wash: 'Machine wash cold inside out.', feat: false, newArr: false, best: false, trend: true, flash: false, fest: true, sizes: MEN_SIZES, colors: [B, GR, N], imgCount: 7 },
  { name: 'Waffle Knit Hoodie', desc: 'Textured waffle knit hoodie with relaxed fit. Three-panel hood, kangaroo pocket, ribbed trims. Waffle texture adds visual interest and cozy warmth.', short: 'Waffle knit texture hoodie', tags: 'hoodie,waffle-knit,textured,comfort', gender: 'MEN', base: 2699, sale: 1899, sku: 'M-HD-505', catSlug: 'men-hoodies', brandSlug: 'classic-threads', fabric: 'Waffle Knit', material: '70% Cotton, 30% Polyester', wash: 'Machine wash cold on gentle.', feat: false, newArr: true, best: false, trend: false, flash: true, fest: false, sizes: MEN_SIZES, colors: [BG, GR, B], imgCount: 7 },

  // ===== WOMEN DRESSES (8) =====
  { name: 'Floral Wrap Dress', desc: 'Flattering wrap dress with vibrant all-over floral print. Lightweight viscose with flowing drape. V-neckline, short flutter sleeves, and tie waist. Perfect for brunch and garden parties.', short: 'Floral print viscose wrap dress', tags: 'dress,wrap,floral,summer,viscose', gender: 'WOMEN', base: 2999, sale: 1999, sku: 'W-DR-601', catSlug: 'women-dresses', brandSlug: 'premium-wear', fabric: 'Viscose', material: '100% Viscose', wash: 'Hand wash cold.', feat: true, newArr: true, best: true, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [R, BL, G], imgCount: 7 },
  { name: 'Little Black Dress', desc: 'Timeless LBD with fitted bodice, sweetheart neckline, and flared mini skirt. Premium crepe with slight stretch. The perfect canvas for statement jewelry.', short: 'Classic LBD in premium crepe', tags: 'dress,party,black,cocktail,classic', gender: 'WOMEN', base: 3999, sale: 2799, sku: 'W-DR-602', catSlug: 'women-dresses', brandSlug: 'elite-collection', fabric: 'Crepe', material: '95% Polyester, 5% Spandex', wash: 'Dry clean recommended.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B], imgCount: 7 },
  { name: 'Tiered Maxi Dress', desc: 'Romantic tiered maxi dress in soft georgette. Adjustable spaghetti straps, smocked bodice, three flowing tiers. Floor-length silhouette for beach weddings.', short: 'Tiered georgette maxi dress', tags: 'dress,maxi,tiered,georgette,bohemian', gender: 'WOMEN', base: 3499, sale: 2499, sku: 'W-DR-603', catSlug: 'women-dresses', brandSlug: 'urban-style', fabric: 'Georgette', material: '100% Georgette', wash: 'Hand wash cold.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [W, PK, BL], imgCount: 7 },
  { name: 'Bodycon Ruched Dress', desc: 'Figure-hugging bodycon dress with ruching detail. Strategic ruching creates flattering gathered effect. Stretch jersey with excellent recovery.', short: 'Bodycon dress with side ruching', tags: 'dress,bodycon,ruched,party,sexy', gender: 'WOMEN', base: 2499, sale: 1799, sku: 'W-DR-604', catSlug: 'women-dresses', brandSlug: 'street-vogue', fabric: 'Jersey', material: '92% Viscose, 8% Elastane', wash: 'Machine wash cold delicate.', feat: false, newArr: false, best: true, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, R, N], imgCount: 7 },
  { name: 'Shirt Dress - Office Edit', desc: 'Polished shirt dress with belted waist and button-through front. Crisp cotton poplin with structured collar and cuffed sleeves. Midi length for office elegance.', short: 'Cotton shirt dress with belt', tags: 'dress,shirt,formal,office,cotton', gender: 'WOMEN', base: 3299, sale: 2299, sku: 'W-DR-605', catSlug: 'women-dresses', brandSlug: 'classic-threads', fabric: 'Cotton Poplin', material: '100% Cotton', wash: 'Machine wash cold.', feat: false, newArr: false, best: false, trend: false, flash: true, fest: false, sizes: WOMEN_SIZES, colors: [W, BL, N], imgCount: 7 },
  { name: 'Satin Slip Dress', desc: 'Luxurious satin slip dress with delicate spaghetti straps and bias cut. Cowl neckline adds glamour, side slit allows movement. Wear solo or layer.', short: 'Satin bias-cut slip dress', tags: 'dress,satin,slip,evening,luxury', gender: 'WOMEN', base: 2799, sale: 1999, sku: 'W-DR-606', catSlug: 'women-dresses', brandSlug: 'elite-collection', fabric: 'Satin', material: '100% Polyester Satin', wash: 'Hand wash cold in mild detergent.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, G, BG], imgCount: 7 },
  { name: 'Boho Midi Dress', desc: 'Free-spirited bohemian midi dress with paisley print and tiered skirt. V-neckline, bell sleeves, tassel tie details. Soft rayon with flowing silhouette.', short: 'Paisley boho midi dress', tags: 'dress,boho,bohemian,paisley,midi', gender: 'WOMEN', base: 2699, sale: 1899, sku: 'W-DR-607', catSlug: 'women-dresses', brandSlug: 'street-vogue', fabric: 'Rayon', material: '100% Rayon', wash: 'Hand wash cold.', feat: false, newArr: false, best: false, trend: true, flash: false, fest: true, sizes: WOMEN_SIZES, colors: [BL, R, G], imgCount: 7 },
  { name: 'A-Line Midi Dress', desc: 'Classic A-line midi dress with fitted bodice and flared skirt. Structured crepe holds its shape. Round neckline, cap sleeves, concealed back zip.', short: 'A-line crepe midi dress', tags: 'dress,a-line,midi,crepe,versatile', gender: 'WOMEN', base: 3199, sale: 2199, sku: 'W-DR-608', catSlug: 'women-dresses', brandSlug: 'modern-fit', fabric: 'Crepe', material: '95% Polyester, 5% Spandex', wash: 'Machine wash cold gentle.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, N, MR], imgCount: 7 },

  // ===== WOMEN KURTIS (7) =====
  { name: 'Anarkali Floor-Length Kurti', desc: 'Graceful Anarkali kurti with floor-length flared hemline. Luxurious rayon with intricate foil printing. Round neckline with golden piping, three-quarter sleeves.', short: 'Floor-length Anarkali kurti', tags: 'kurti,anarkali,festive,rayon,elegant', gender: 'WOMEN', base: 2999, sale: 2099, sku: 'W-KU-701', catSlug: 'women-kurtis', brandSlug: 'premium-wear', fabric: 'Rayon', material: '100% Rayon', wash: 'Hand wash cold. Dry in shade.', feat: true, newArr: true, best: true, trend: false, flash: false, fest: true, sizes: WOMEN_SIZES, colors: [N, MR, G], imgCount: 7 },
  { name: 'Cotton Straight-Cut Kurti', desc: 'Everyday cotton kurti with straight-cut silhouette and three-quarter sleeves. Mandarin collar with button placket. Breathable cotton for daily and office wear.', short: 'Cotton straight-cut daily kurti', tags: 'kurti,cotton,straight,daily-wear,office', gender: 'WOMEN', base: 1499, sale: 999, sku: 'W-KU-702', catSlug: 'women-kurtis', brandSlug: 'classic-threads', fabric: 'Cotton', material: '100% Cotton', wash: 'Machine wash cold.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [W, BL, G, PK], imgCount: 7 },
  { name: 'Printed A-Line Kurti', desc: 'Vibrant A-line kurti with all-over block print. Soft cotton with flared hemline. V-neckline with tassel detail and three-quarter bell sleeves.', short: 'Block print A-line kurti', tags: 'kurti,a-line,printed,block-print,cotton', gender: 'WOMEN', base: 1799, sale: 1299, sku: 'W-KU-703', catSlug: 'women-kurtis', brandSlug: 'urban-style', fabric: 'Cotton', material: '100% Cotton', wash: 'Hand wash in cold water.', feat: false, newArr: false, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [BL, R, G], imgCount: 7 },
  { name: 'Sharara Set Kurti', desc: 'Contemporary sharara set with short kurti and flared sharara pants. Georgette with sequin embellishments and scalloped edges. Perfect for sangeet and celebrations.', short: 'Georgette sharara set with kurti', tags: 'kurti,sharara,set,georgette,festive,party', gender: 'WOMEN', base: 4999, sale: 3499, sku: 'W-KU-704', catSlug: 'women-kurtis', brandSlug: 'elite-collection', fabric: 'Georgette', material: '100% Georgette with Sequin Work', wash: 'Dry clean only.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [MR, N, G], imgCount: 7 },
  { name: 'Indigo Dye Kurti', desc: 'Hand-dyed indigo kurti with traditional Bandhani pattern. Pure cotton with artisanal finish. Each piece is unique. Celebrates Indian craftsmanship.', short: 'Hand-dyed indigo Bandhani kurti', tags: 'kurti,indigo,bandhani,handmade,artisan', gender: 'WOMEN', base: 2299, sale: 1699, sku: 'W-KU-705', catSlug: 'women-kurtis', brandSlug: 'classic-threads', fabric: 'Cotton', material: '100% Handloom Cotton', wash: 'Hand wash separately first 3 washes.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [BL, N], imgCount: 7 },
  { name: 'Embroidered Kurta Set', desc: 'Elegant kurta set with long kurta and matching palazzo pants. Intricate thread embroidery on neckline and hem. Soft rayon with relaxed fit.', short: 'Embroidered kurta with palazzo', tags: 'kurti,kurta,set,palazzo,embroidered,festive', gender: 'WOMEN', base: 3499, sale: 2499, sku: 'W-KU-706', catSlug: 'women-kurtis', brandSlug: 'premium-wear', fabric: 'Rayon', material: '100% Rayon with Thread Embroidery', wash: 'Hand wash cold.', feat: false, newArr: false, best: true, trend: false, flash: true, fest: false, sizes: WOMEN_SIZES, colors: [B, MR, G], imgCount: 7 },
  { name: 'Cape Style Kurti', desc: 'Statement cape-style kurti with attached cape overlay. Flowing georgette with satin lining. Cape adds contemporary edge to traditional silhouette.', short: 'Cape overlay georgette kurti', tags: 'kurti,cape,georgette,contemporary,dramatic', gender: 'WOMEN', base: 2799, sale: 1999, sku: 'W-KU-707', catSlug: 'women-kurtis', brandSlug: 'modern-fit', fabric: 'Georgette', material: '100% Georgette with Satin Lining', wash: 'Dry clean recommended.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, N, BG], imgCount: 7 },

  // ===== WOMEN TOPS (7) =====
  { name: 'Ruched Crop Top', desc: 'Trendy ruched crop top with adjustable side drawstrings. Ribbed knit fabric with body-hugging fit. Square neckline and cap sleeves.', short: 'Ribbed ruched crop top', tags: 'top,crop,ruched,ribbed,trendy', gender: 'WOMEN', base: 999, sale: 699, sku: 'W-TP-801', catSlug: 'women-tops', brandSlug: 'street-vogue', fabric: 'Ribbed Knit', material: '95% Viscose, 5% Elastane', wash: 'Machine wash cold delicate.', feat: false, newArr: true, best: true, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, W, PK, G], imgCount: 7 },
  { name: 'Peplum Blouse', desc: 'Feminine peplum blouse with fitted bodice and flared peplum waist. Structured crepe, V-neckline, three-quarter sleeves. Cinches waist for hourglass silhouette.', short: 'Crepe peplum blouse', tags: 'top,peplum,blouse,feminine,office', gender: 'WOMEN', base: 1699, sale: 1199, sku: 'W-TP-802', catSlug: 'women-tops', brandSlug: 'elite-collection', fabric: 'Crepe', material: '95% Polyester, 5% Spandex', wash: 'Machine wash cold. Hang dry.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [W, B, N], imgCount: 7 },
  { name: 'Oversized Graphic Tee', desc: 'Relaxed oversized tee with bold front graphic. Heavyweight cotton with dropped shoulder. Boxy fit and extended length for laid-back streetwear aesthetic.', short: 'Oversized graphic cotton tee', tags: 'top,t-shirt,oversized,graphic,streetwear', gender: 'WOMEN', base: 1299, sale: 899, sku: 'W-TP-803', catSlug: 'women-tops', brandSlug: 'street-vogue', fabric: 'Cotton', material: '100% Cotton 200 GSM', wash: 'Turn inside out. Cold wash.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [W, B, GR], imgCount: 7 },
  { name: 'Organza Puff Sleeve Top', desc: 'Statement organza top with dramatic puff sleeves and fitted bodice. Sheer organza sleeves create romantic editorial look. Sweetheart neckline.', short: 'Organza puff sleeve top', tags: 'top,organza,puff-sleeve,romantic,statement', gender: 'WOMEN', base: 1899, sale: 1399, sku: 'W-TP-804', catSlug: 'women-tops', brandSlug: 'premium-wear', fabric: 'Organza', material: '100% Polyester Organza', wash: 'Hand wash cold.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [W, PK, B], imgCount: 7 },
  { name: 'Linen Summer Top', desc: 'Breezy linen top with relaxed fit and camp collar. Pure linen that softens with each wash. Boxy cut with side slits for maximum airflow.', short: 'Pure linen camp collar top', tags: 'top,linen,summer,relaxed,beach', gender: 'WOMEN', base: 1799, sale: 1299, sku: 'W-TP-805', catSlug: 'women-tops', brandSlug: 'classic-threads', fabric: 'Linen', material: '100% Linen', wash: 'Hand wash or gentle machine wash.', feat: false, newArr: false, best: false, trend: false, flash: true, fest: false, sizes: WOMEN_SIZES, colors: [W, BG, BL], imgCount: 7 },
  { name: 'Sequin Party Top', desc: 'Show-stopping sequin top with full sequin embellishment. Round neckline, long sleeves, back zip closure. Fully lined for comfort. Perfect for celebrations.', short: 'Full sequin party top', tags: 'top,sequin,party,glamorous,celebration', gender: 'WOMEN', base: 2499, sale: 1799, sku: 'W-TP-806', catSlug: 'women-tops', brandSlug: 'elite-collection', fabric: 'Sequin Mesh', material: 'Polyester with Sequin', wash: 'Hand wash cold only.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: true, sizes: WOMEN_SIZES, colors: [B, GL, SV], imgCount: 7 },
  { name: 'Knit V-Neck Sweater', desc: 'Cozy knit sweater with V-neckline and relaxed fit. Soft acrylic-cotton blend with chunky knit texture. Ribbed trims and slightly cropped length.', short: 'Chunky knit V-neck sweater', tags: 'top,sweater,knit,v-neck,winter', gender: 'WOMEN', base: 1999, sale: 1399, sku: 'W-TP-807', catSlug: 'women-tops', brandSlug: 'urban-style', fabric: 'Acrylic Cotton Blend', material: '60% Acrylic, 40% Cotton', wash: 'Hand wash cold. Lay flat to dry.', feat: false, newArr: false, best: false, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [GR, BG, N, PK], imgCount: 7 },

  // ===== WOMEN SAREES (5) =====
  { name: 'Banarasi Silk Saree', desc: 'Exquisite Banarasi silk saree with intricate gold zari weaving and lavish pallu. Comes with matching blouse piece. Rich silk drapes beautifully for weddings and grand celebrations.', short: 'Gold zari Banarasi silk saree', tags: 'saree,silk,banarasi,wedding,luxury,gold', gender: 'WOMEN', base: 8999, sale: 6499, sku: 'W-SR-901', catSlug: 'women-sarees', brandSlug: 'premium-wear', fabric: 'Banarasi Silk', material: '100% Pure Silk with Gold Zari', wash: 'Dry clean only.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: true, sizes: ['FREE SIZE'], colors: [MR, G, N], imgCount: 8 },
  { name: 'Chiffon Printed Saree', desc: 'Lightweight chiffon saree with digital floral print. Easy to drape with natural fall. Comes with matching blouse material. Sheer chiffon creates elegant silhouette.', short: 'Printed chiffon saree with blouse', tags: 'saree,chiffon,printed,floral,lightweight', gender: 'WOMEN', base: 2999, sale: 1999, sku: 'W-SR-902', catSlug: 'women-sarees', brandSlug: 'urban-style', fabric: 'Chiffon', material: '100% Georgette Chiffon', wash: 'Hand wash cold.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: ['FREE SIZE'], colors: [BL, PK, G], imgCount: 7 },
  { name: 'Cotton Handloom Saree', desc: 'Authentic handloom cotton saree with traditional temple border. Hand-spun, hand-woven cotton for breathability. Natural texture celebrates artisan craft.', short: 'Handloom cotton with temple border', tags: 'saree,cotton,handloom,traditional,artisan', gender: 'WOMEN', base: 3499, sale: 2499, sku: 'W-SR-903', catSlug: 'women-sarees', brandSlug: 'classic-threads', fabric: 'Handloom Cotton', material: '100% Hand-spun Hand-woven Cotton', wash: 'Hand wash cold first 3 washes.', feat: true, newArr: false, best: false, trend: false, flash: false, fest: false, sizes: ['FREE SIZE'], colors: [W, BL, YL], imgCount: 7 },
  { name: 'Satin Party Saree', desc: 'Glamorous satin saree with lustrous finish. Sequin-embellished border and pallu. Comes with heavily embellished blouse piece. Drapes like liquid gold.', short: 'Sequin border satin saree', tags: 'saree,satin,party,glamorous,sequin', gender: 'WOMEN', base: 5999, sale: 4199, sku: 'W-SR-904', catSlug: 'women-sarees', brandSlug: 'elite-collection', fabric: 'Satin', material: '100% Poly Satin with Sequin', wash: 'Dry clean only.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: ['FREE SIZE'], colors: [B, G, MR], imgCount: 7 },
  { name: 'Organza Tissue Saree', desc: 'Ethereal organza tissue saree with shimmering metallic sheen. Delicate scalloped border with pearl detailing. Stiff yet lightweight for structured drapes.', short: 'Metallic organza tissue saree', tags: 'saree,organza,tissue,metallic,elegant', gender: 'WOMEN', base: 7499, sale: 5499, sku: 'W-SR-905', catSlug: 'women-sarees', brandSlug: 'elite-collection', fabric: 'Organza Tissue', material: 'Organza with Metallic Tissue', wash: 'Dry clean only.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: ['FREE SIZE'], colors: [GL, SV, PK], imgCount: 7 },

  // ===== KIDS (8) =====
  { name: 'Printed Cotton T-Shirt Set', desc: 'Value pack of three cotton t-shirts in fun prints. Soft, breathable cotton gentle on kids skin. Pre-shrunk fabric with reinforced seams.', short: '3-pack printed cotton tees', tags: 'kids,t-shirt,set,cotton,printed,value-pack', gender: 'KIDS', base: 1299, sale: 899, sku: 'K-TS-001', catSlug: 'kids-t-shirts', brandSlug: 'premium-wear', fabric: 'Cotton', material: '100% Cotton 160 GSM', wash: 'Machine wash cold.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: KID_SIZES, colors: [BL, R, G], imgCount: 7 },
  { name: 'Denim Overalls', desc: 'Adorable denim overalls with adjustable straps and snap-button closures. Front bib pocket and side pockets. Soft stretch denim for active kids.', short: 'Stretch denim kids overalls', tags: 'kids,overalls,denim,classic,cute', gender: 'KIDS', base: 1799, sale: 1299, sku: 'K-JN-001', catSlug: 'kids-jeans', brandSlug: 'urban-style', fabric: 'Stretch Denim', material: '98% Cotton, 2% Elastane', wash: 'Machine wash cold inside out.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: KID_SIZES, colors: [BL, B], imgCount: 7 },
  { name: 'Princess Party Dress', desc: 'Enchanting princess dress with tulle skirt and satin bodice. V-neckline with lace trim, concealed back zip, built-in petticoat for volume.', short: 'Tulle princess party dress', tags: 'kids,dress,princess,party,tulle', gender: 'KIDS', base: 2499, sale: 1799, sku: 'K-DR-001', catSlug: 'kids-dresses', brandSlug: 'elite-collection', fabric: 'Tulle & Satin', material: '100% Polyester Tulle', wash: 'Hand wash cold.', feat: true, newArr: true, best: true, trend: false, flash: false, fest: false, sizes: KID_SIZES, colors: [PK, W, BL], imgCount: 7 },
  { name: 'Superhero Graphic Hoodie', desc: 'Fun superhero-themed hoodie with bold chest graphic and matching hood lining. Warm cotton fleece with kangaroo pocket. Sparks imagination.', short: 'Superhero graphic kids hoodie', tags: 'kids,hoodie,superhero,graphic,fun', gender: 'KIDS', base: 1499, sale: 999, sku: 'K-HD-001', catSlug: 'kids-t-shirts', brandSlug: 'street-vogue', fabric: 'Cotton Fleece', material: '80% Cotton, 20% Polyester', wash: 'Machine wash cold.', feat: false, newArr: false, best: true, trend: true, flash: false, fest: false, sizes: KID_SIZES, colors: [BL, R, B], imgCount: 7 },
  { name: 'Floral Summer Dress', desc: 'Sweet floral print dress in lightweight cotton voile. Peter Pan collar, short puff sleeves, gathered waist with ribbon tie. Perfect for warm-weather adventures.', short: 'Cotton floral summer dress', tags: 'kids,dress,floral,summer,cotton', gender: 'KIDS', base: 1699, sale: 1199, sku: 'K-DR-002', catSlug: 'kids-dresses', brandSlug: 'classic-threads', fabric: 'Cotton Voile', material: '100% Cotton', wash: 'Machine wash cold gentle.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: KID_SIZES, colors: [PK, YL, BL], imgCount: 7 },
  { name: 'Cargo Jogger Pants', desc: 'Durable cargo joggers with elastic waistband and adjustable cuffs. Side cargo pockets and reinforced knees. Tough cotton twill for active play.', short: 'Durable cargo joggers for kids', tags: 'kids,jogger,cargo,pants,durable,active', gender: 'KIDS', base: 1299, sale: 899, sku: 'K-TR-001', catSlug: 'kids-trousers', brandSlug: 'urban-style', fabric: 'Cotton Twill', material: '100% Cotton', wash: 'Machine wash cold.', feat: false, newArr: false, best: false, trend: true, flash: true, fest: false, sizes: KID_SIZES, colors: [G, B, BG], imgCount: 7 },
  { name: 'Traditional Kurta Pyjama Set', desc: 'Handsome traditional kurta pyjama set. Woven jacquard kurta with mandarin collar, paired with elastic-waist pyjama pants. Perfect for festivals.', short: 'Jacquard kurta pyjama set', tags: 'kids,kurta,pyjama,traditional,festive', gender: 'KIDS', base: 1999, sale: 1499, sku: 'K-TR-002', catSlug: 'kids-traditional', brandSlug: 'premium-wear', fabric: 'Cotton Jacquard', material: '100% Cotton', wash: 'Hand wash cold.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: true, sizes: KID_SIZES, colors: [N, W, MR], imgCount: 7 },
  { name: 'Winter Fleece Jacket', desc: 'Warm fleece jacket with full-zip front and stand collar. Anti-pill fleece stays soft wash after wash. Elasticated cuffs and zippered pockets.', short: 'Anti-pill fleece winter jacket', tags: 'kids,jacket,fleece,winter,warm', gender: 'KIDS', base: 1799, sale: 1299, sku: 'K-JK-001', catSlug: 'kids-t-shirts', brandSlug: 'elite-collection', fabric: 'Anti-Pill Fleece', material: '100% Polyester Fleece', wash: 'Machine wash cold.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: KID_SIZES, colors: [BL, R, G], imgCount: 7 },

  // ===== ACCESSORIES (8) =====
  { name: 'Leather Messenger Bag', desc: 'Handcrafted full-grain leather messenger bag with adjustable strap. Flap closure with brass buckle, padded laptop compartment (15"), organizer pockets. Ages beautifully.', short: 'Full-grain leather messenger bag', tags: 'bag,messenger,leather,premium,laptop', gender: 'ACCESSORIES', base: 5999, sale: 4199, sku: 'A-BG-001', catSlug: 'accessories-bags', brandSlug: 'elite-collection', fabric: 'Full-Grain Leather', material: '100% Vegetable-Tanned Leather', wash: 'Wipe with damp cloth.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: ['ONE SIZE'], colors: [B, BR, TN], imgCount: 7 },
  { name: 'Canvas Adventure Backpack', desc: 'Rugged canvas backpack for everyday adventures. Padded laptop sleeve, water bottle pockets, airflow back panel. Roll-top closure with waxed canvas water resistance.', short: 'Waxed canvas adventure backpack', tags: 'bag,backpack,canvas,adventure,travel', gender: 'ACCESSORIES', base: 3499, sale: 2499, sku: 'A-BG-002', catSlug: 'accessories-bags', brandSlug: 'street-vogue', fabric: 'Waxed Canvas', material: '100% Waxed Cotton Canvas', wash: 'Spot clean. Re-wax annually.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: ['ONE SIZE'], colors: [G, N, B], imgCount: 7 },
  { name: 'Classic Leather Belt', desc: 'Timeless leather belt with brushed nickel buckle. Top-grain leather with smooth finish. 1.5" width works for formal and casual.', short: 'Top-grain leather dress belt', tags: 'belt,leather,classic,formal,essential', gender: 'ACCESSORIES', base: 1499, sale: 999, sku: 'A-BL-001', catSlug: 'accessories-belts', brandSlug: 'classic-threads', fabric: 'Top-Grain Leather', material: '100% Leather with Nickel Buckle', wash: 'Wipe clean.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: ['28', '30', '32', '34', '36', '38', '40'], colors: [B, BR], imgCount: 7 },
  { name: 'Aviator Sunglasses', desc: 'Classic aviator sunglasses with polarized lenses and UV400 protection. Lightweight metal frame with adjustable nose pads. Iconic teardrop shape.', short: 'Polarized aviator sunglasses', tags: 'sunglasses,aviator,polarized,uv-protection,classic', gender: 'ACCESSORIES', base: 2499, sale: 1699, sku: 'A-SG-001', catSlug: 'accessories-sunglasses', brandSlug: 'elite-collection', fabric: 'Metal Frame', material: 'Stainless Steel, Polarized CR-39', wash: 'Clean with microfiber cloth.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: ['ONE SIZE'], colors: [B, GL, SV], imgCount: 7 },
  { name: 'Minimalist Analog Watch', desc: 'Sleek minimalist watch with clean dial and genuine leather strap. Japanese quartz movement. Water-resistant to 30m. Ultra-thin 7mm case.', short: 'Minimalist Japanese quartz watch', tags: 'watch,analog,minimalist,leather,premium', gender: 'ACCESSORIES', base: 4999, sale: 3499, sku: 'A-WT-001', catSlug: 'accessories-watches', brandSlug: 'modern-fit', fabric: 'Stainless Steel', material: '316L Stainless Steel, Sapphire Crystal', wash: 'Avoid water. Clean with soft cloth.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: ['ONE SIZE'], colors: [B, BR, N], imgCount: 8 },
  { name: 'Suede Chelsea Boots', desc: 'Refined Chelsea boots in premium suede with elastic side panels. Leather sole with rubber heel grip and Goodyear welt construction.', short: 'Premium suede Chelsea boots', tags: 'boots,chelsea,suede,premium,formal', gender: 'ACCESSORIES', base: 6999, sale: 4999, sku: 'A-FT-001', catSlug: 'footwear-boots', brandSlug: 'elite-collection', fabric: 'Suede', material: '100% Suede Upper, Leather Sole', wash: 'Apply suede protector spray.', feat: true, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: SHOE_SIZES, colors: [B, BR, TN], imgCount: 7 },
  { name: 'Canvas Tote Bag', desc: 'Oversized canvas tote with reinforced handles and magnetic snap closure. Interior zip pocket and slip pockets. Structured base stands upright.', short: 'Structured canvas tote bag', tags: 'bag,tote,canvas,everyday,practical', gender: 'ACCESSORIES', base: 1999, sale: 1399, sku: 'A-BG-003', catSlug: 'accessories-bags', brandSlug: 'urban-style', fabric: 'Canvas', material: '100% Heavyweight Cotton Canvas', wash: 'Machine wash cold.', feat: false, newArr: false, best: true, trend: false, flash: true, fest: false, sizes: ['ONE SIZE'], colors: [BG, B, N], imgCount: 7 },
  { name: 'Wool Herringbone Scarf', desc: 'Luxuriously soft wool scarf with herringbone weave. 100% merino wool for warmth without itchiness. Generous 70" x 12" size. Winter essential.', short: 'Merino wool herringbone scarf', tags: 'scarf,wool,merino,winter,warmth', gender: 'ACCESSORIES', base: 1999, sale: 1399, sku: 'A-SC-001', catSlug: 'accessories-scarves', brandSlug: 'premium-wear', fabric: 'Merino Wool', material: '100% Merino Wool', wash: 'Hand wash cold in wool detergent.', feat: false, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: ['ONE SIZE'], colors: [GR, N, BG, B], imgCount: 7 },

  // ===== FOOTWEAR (8) =====
  { name: 'Classic White Sneakers', desc: 'Timeless white leather sneakers with clean minimalist design. Cushioned insole, durable rubber outsole, reinforced stitching. Foundation of any modern wardrobe.', short: 'Minimalist white leather sneakers', tags: 'sneakers,white,leather,classic,minimalist', gender: 'MEN', base: 3999, sale: 2799, sku: 'M-FT-001', catSlug: 'footwear-sneakers', brandSlug: 'modern-fit', fabric: 'Leather', material: '100% Leather Upper, Rubber Sole', wash: 'Wipe with damp cloth.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: SHOE_SIZES, colors: [W, B], imgCount: 7 },
  { name: 'Running Performance Shoes', desc: 'High-performance running shoes with responsive foam cushioning and breathable mesh upper. Reinforced heel counter and flex groove outsole.', short: 'Performance running shoes', tags: 'shoes,running,performance,sports,athletic', gender: 'MEN', base: 5999, sale: 4199, sku: 'M-FT-002', catSlug: 'footwear-sports-shoes', brandSlug: 'elite-collection', fabric: 'Mesh', material: 'Engineered Mesh, EVA Midsole', wash: 'Hand wash with mild soap.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: SHOE_SIZES, colors: [B, BL, R], imgCount: 7 },
  { name: 'Suede Loafers', desc: 'Elegant suede loafers with hand-stitched apron toe. Cushioned footbed and flexible leather outsole. Penny loafer design for casual to semi-formal.', short: 'Suede penny loafers', tags: 'loafers,suede,formal,classic,preppy', gender: 'MEN', base: 4499, sale: 3199, sku: 'M-FT-003', catSlug: 'footwear-formal-shoes', brandSlug: 'classic-threads', fabric: 'Suede', material: 'Suede Upper, Leather Sole', wash: 'Apply suede protector.', feat: false, newArr: false, best: false, trend: false, flash: false, fest: false, sizes: SHOE_SIZES, colors: [TN, BR, B], imgCount: 7 },
  { name: 'Platform Chunky Sneakers', desc: 'Statement chunky sneakers with exaggerated platform sole. Mixed-material upper combining leather, mesh, and synthetic. Adds 3 inches of height.', short: 'Platform chunky sneakers', tags: 'sneakers,chunky,platform,statement,trendy', gender: 'WOMEN', base: 4999, sale: 3499, sku: 'W-FT-001', catSlug: 'footwear-sneakers', brandSlug: 'street-vogue', fabric: 'Mixed Materials', material: 'Leather, Mesh, Synthetic', wash: 'Wipe clean with damp cloth.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [W, B, PK], imgCount: 7 },
  { name: 'Kolhapuri Chappals', desc: 'Handcrafted Kolhapuri chappals in genuine leather with traditional braided strap. Made by skilled artisans. Vegetable-tanned leather molds to your foot.', short: 'Handcrafted leather Kolhapuri chappals', tags: 'chappals,kolhapuri,leather,handmade,traditional', gender: 'WOMEN', base: 1999, sale: 1499, sku: 'W-FT-002', catSlug: 'footwear-sandals', brandSlug: 'classic-threads', fabric: 'Leather', material: '100% Vegetable-Tanned Leather', wash: 'Avoid water. Clean with leather conditioner.', feat: true, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [BR, TN], imgCount: 7 },
  { name: 'Sport Running Shoes', desc: 'Lightweight sport running shoes with responsive cushioning. Breathable flyknit upper and carbon rubber outsole. Multi-directional traction patterns.', short: 'Lightweight sport running shoes', tags: 'shoes,sport,running,lightweight,performance', gender: 'MEN', base: 6499, sale: 4499, sku: 'M-FT-004', catSlug: 'footwear-sports-shoes', brandSlug: 'premium-wear', fabric: 'Flyknit', material: 'Flyknit Upper, Carbon Rubber Outsole', wash: 'Hand wash in cold water.', feat: false, newArr: true, best: false, trend: false, flash: true, fest: false, sizes: SHOE_SIZES, colors: [B, GR, BL], imgCount: 7 },
  { name: 'Woven Leather Sandals', desc: 'Artisanal woven leather sandals with comfortable flat sole. Hand-woven genuine leather straps in intricate basket-weave pattern. Adjustable ankle strap.', short: 'Hand-woven leather flat sandals', tags: 'sandals,leather,woven,summer,artisan', gender: 'WOMEN', base: 2499, sale: 1799, sku: 'W-FT-003', catSlug: 'footwear-sandals', brandSlug: 'premium-wear', fabric: 'Leather', material: '100% Hand-woven Leather', wash: 'Wipe with damp cloth.', feat: false, newArr: false, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [TN, B, BR], imgCount: 7 },
  { name: 'Platform Combat Boots', desc: 'Edgy platform combat boots with chunky lug sole. Lace-up front with metal eyelets, padded collar, pull tab at heel. Height and attitude.', short: 'Chunky platform combat boots', tags: 'boots,combat,platform,edgy,statement', gender: 'WOMEN', base: 4999, sale: 3499, sku: 'W-FT-004', catSlug: 'footwear-boots', brandSlug: 'street-vogue', fabric: 'Faux Leather', material: 'Faux Leather Upper, Rubber Sole', wash: 'Wipe with damp cloth.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, BR], imgCount: 7 },

  // ===== EXTRA MEN (3) =====
  { name: 'Tapered Fit Chinos', desc: 'Modern tapered chinos in cotton-stretch twill. Flat front with a tapered leg that narrows toward the ankle. Features a button closure with zip fly and multiple pockets. Versatile enough for office or weekend wear.', short: 'Cotton-stretch tapered chinos', tags: 'chinos,tapered,cotton,smart-casual,office', gender: 'MEN', base: 2299, sale: 1599, sku: 'M-TR-601', catSlug: 'men-trousers', brandSlug: 'modern-fit', fabric: 'Cotton Twill', material: '97% Cotton, 3% Elastane', wash: 'Machine wash cold. Tumble dry low.', feat: false, newArr: true, best: true, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [KHAKI, N, B, BG], imgCount: 7 },
  { name: 'Pleated Formal Trousers', desc: 'Classic pleated formal trousers in a wool-blend fabric. Double pleats create a relaxed silhouette through the thigh. Features a high-rise waist, pressed creases, and a tapered hem. Perfect for formal and business settings.', short: 'Wool-blend pleated formal trousers', tags: 'trousers,formal,pleated,wool,office', gender: 'MEN', base: 3499, sale: 2499, sku: 'M-TR-602', catSlug: 'men-trousers', brandSlug: 'elite-collection', fabric: 'Wool Blend', material: '60% Wool, 40% Polyester', wash: 'Dry clean recommended.', feat: true, newArr: false, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [B, N, GR], imgCount: 7 },
  { name: 'Tailored Wool Blazer', desc: 'Sharp tailored blazer in premium Italian wool. Two-button closure with notch lapel, fully canvassed construction, and dual back vents. The structured shoulder and tapered waist create a powerful silhouette.', short: 'Italian wool tailored blazer', tags: 'blazer,wool,tailored,formal,premium', gender: 'MEN', base: 9999, sale: 7499, sku: 'M-BZ-601', catSlug: 'men-blazers', brandSlug: 'elite-collection', fabric: 'Italian Wool', material: '100% Italian Super 120s Wool', wash: 'Dry clean only.', feat: true, newArr: true, best: false, trend: false, flash: false, fest: false, sizes: MEN_SIZES, colors: [N, GR, B], imgCount: 8 },

  // ===== EXTRA WOMEN (3) =====
  { name: 'High-Rise Palazzo Pants', desc: 'Flowing palazzo pants with a flattering high-rise waist and wide leg. Made from soft rayon with a smooth drape. Features a side zip closure and elastic waistband for comfort. Pairs beautifully with fitted tops and kurtis.', short: 'Flowing rayon palazzo pants', tags: 'palazzo,high-rise,flowing,comfortable,elegant', gender: 'WOMEN', base: 1699, sale: 1199, sku: 'W-PL-801', catSlug: 'women-palazzo', brandSlug: 'premium-wear', fabric: 'Rayon', material: '100% Rayon', wash: 'Hand wash cold. Hang dry.', feat: false, newArr: true, best: true, trend: false, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, N, W, BG], imgCount: 7 },
  { name: 'Pleated A-Line Skirt', desc: 'Elegant pleated A-line skirt in premium polyester with a satiny finish. Knife pleats create beautiful movement and the midi length adds sophistication. High-rise waist with invisible back zip.', short: 'Pleated midi A-line skirt', tags: 'skirt,pleated,a-line,midi,elegant,office', gender: 'WOMEN', base: 2199, sale: 1599, sku: 'W-SK-801', catSlug: 'women-skirts', brandSlug: 'modern-fit', fabric: 'Polyester Satin', material: '100% Polyester', wash: 'Machine wash cold gentle. Hang dry.', feat: false, newArr: false, best: false, trend: true, flash: false, fest: false, sizes: WOMEN_SIZES, colors: [B, N, BG], imgCount: 7 },
  { name: 'Embroidered Anarkali Suit Set', desc: 'Magnificent Anarkali suit set with heavy thread and mirror work embroidery. Includes flared floor-length Anarkali, churidar, and matching dupatta. Made from rich art silk with gold accents. A showstopper for weddings.', short: 'Embroidered art silk Anarkali set', tags: 'anarkali,suit,set,embroidered,festive,wedding,luxury', gender: 'WOMEN', base: 6999, sale: 4999, sku: 'W-KU-708', catSlug: 'women-kurtis', brandSlug: 'elite-collection', fabric: 'Art Silk', material: 'Art Silk with Thread & Mirror Work', wash: 'Dry clean only.', feat: true, newArr: true, best: false, trend: true, flash: false, fest: true, sizes: WOMEN_SIZES, colors: [MR, N, G], imgCount: 8 },

  // ===== EXTRA KIDS (3) =====
  { name: 'Cartoon Print Pyjama Set', desc: 'Cozy cotton pyjama set with fun cartoon prints. Soft elastic waistband with drawstring. Breathable cotton keeps little ones comfortable all night. A bedtime favorite.', short: 'Cotton cartoon print pyjama set', tags: 'kids,pyjama,set,cartoon,cotton,sleepwear', gender: 'KIDS', base: 999, sale: 699, sku: 'K-NW-001', catSlug: 'kids-nightwear', brandSlug: 'premium-wear', fabric: 'Cotton Jersey', material: '100% Cotton 160 GSM', wash: 'Machine wash cold.', feat: false, newArr: false, best: true, trend: false, flash: true, fest: false, sizes: KID_SIZES, colors: [BL, PK, G], imgCount: 7 },
  { name: 'Sporty Track Pants', desc: 'Comfortable track pants with side stripe detailing. Elastic waistband with drawstring and zippered ankles. Breathable polyester tricot with moisture-wicking. Perfect for sports and casual.', short: 'Polyester tricot track pants', tags: 'kids,track-pants,sports,active,comfortable', gender: 'KIDS', base: 1199, sale: 849, sku: 'K-TR-003', catSlug: 'kids-activewear', brandSlug: 'street-vogue', fabric: 'Polyester Tricot', material: '100% Polyester with Moisture Wicking', wash: 'Machine wash cold. Tumble dry low.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: KID_SIZES, colors: [B, N, GR], imgCount: 7 },
  { name: 'Ruffle Hem Party Dress', desc: 'Adorable ruffle hem dress with layered tulle skirt and sequin-embellished bodice. Sleeveless design with snap button closure. Twirl-worthy for birthday parties and special occasions.', short: 'Ruffle hem tulle party dress', tags: 'kids,dress,party,ruffle,tulle,sequin', gender: 'KIDS', base: 2199, sale: 1599, sku: 'K-DR-003', catSlug: 'kids-dresses', brandSlug: 'premium-wear', fabric: 'Tulle & Sequin', material: 'Polyester Tulle with Sequin Panel', wash: 'Hand wash cold.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: true, sizes: KID_SIZES, colors: [PK, GL, R], imgCount: 7 },

  // ===== EXTRA ACCESSORIES (2) =====
  { name: 'Leather Card Holder Wallet', desc: 'Slim leather card holder with RFID blocking technology. 4 card slots and center cash compartment. Premium cowhide leather with refined grain finish. Fits front pocket perfectly.', short: 'RFID blocking leather card holder', tags: 'wallet,card-holder,leather,rfid,slim', gender: 'ACCESSORIES', base: 1299, sale: 899, sku: 'A-WL-001', catSlug: 'accessories-wallets', brandSlug: 'classic-threads', fabric: 'Leather', material: '100% Cowhide Leather', wash: 'Wipe clean with dry cloth.', feat: false, newArr: false, best: true, trend: false, flash: false, fest: false, sizes: ['ONE SIZE'], colors: [B, BR, N], imgCount: 7 },
  { name: 'Stainless Steel Bracelet', desc: 'Premium stainless steel bracelet with modern chain link design. Polished and brushed dual finish. Secure clasp closure. Hypoallergenic and tarnish-resistant for everyday wear.', short: 'Stainless steel chain bracelet', tags: 'jewellery,bracelet,steel,modern,premium', gender: 'ACCESSORIES', base: 1999, sale: 1399, sku: 'A-JW-001', catSlug: 'accessories-jewellery', brandSlug: 'modern-fit', fabric: 'Stainless Steel', material: '316L Stainless Steel', wash: 'Clean with soft damp cloth.', feat: false, newArr: true, best: false, trend: true, flash: false, fest: false, sizes: ['ONE SIZE'], colors: [SV, GL, B], imgCount: 7 },

  // ===== EXTRA FOOTWEAR (1) =====
  { name: 'Leather Flip Flops', desc: 'Premium leather flip flops with contoured footbed for arch support. Genuine leather straps with suede lining. Durable rubber outsole with non-slip tread. Elevates the basic flip flop.', short: 'Premium leather flip flops', tags: 'flip-flops,leather,premium,summer,beach', gender: 'MEN', base: 1799, sale: 1299, sku: 'M-FT-005', catSlug: 'footwear-slippers', brandSlug: 'premium-wear', fabric: 'Leather', material: 'Genuine Leather Straps, Rubber Sole', wash: 'Wipe clean.', feat: false, newArr: false, best: false, trend: false, flash: true, fest: false, sizes: SHOE_SIZES, colors: [B, BR, TN], imgCount: 7 },
];

async function login(): Promise<string> {
  const creds = [
    { email: 'rajakajaykumar686@gmail.com', password: '@Kareena.com201522' },
    { email: 'admin@storename.com', password: 'admin123' },
  ];
  for (const c of creds) {
    try {
      const res = await fetch(`${API}/auth/login`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(c),
      });
      const data: any = await res.json();
      if (data.success && data.data?.accessToken) {
        console.log(`Logged in as ${c.email}`);
        return data.data.accessToken;
      }
    } catch {}
  }
  throw new Error('Login failed with all credentials');
}

async function apiGet(path: string, token: string): Promise<any> {
  const res = await fetch(`${API}${path}`, { headers: { Authorization: `Bearer ${token}` } });
  return res.json();
}

async function apiPost(path: string, body: any, token: string): Promise<any> {
  const res = await fetch(`${API}${path}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
    body: JSON.stringify(body),
  });
  return res.json();
}

async function main() {
  console.log('=== Seeding 100 Products via API ===\n');

  const token = await login();

  const catRes: any = await apiGet('/categories', token);
  const cats: any[] = catRes.data || catRes || [];
  const catMap: Record<string, string> = {};
  for (const c of cats) catMap[c.slug] = c.id;
  console.log(`Found ${cats.length} categories`);

  const brandRes: any = await apiGet('/brands', token);
  const brands: any[] = brandRes.data || brandRes || [];
  const brandMap: Record<string, string> = {};
  for (const b of brands) brandMap[b.slug] = b.id;
  console.log(`Found ${brands.length} brands`);

  let created = 0;
  let failed = 0;
  let skipped = 0;

  for (const p of products) {
    const catId = catMap[p.catSlug];
    if (!catId) {
      console.log(`  SKIP: category "${p.catSlug}" not found for "${p.name}"`);
      skipped++;
      continue;
    }

    const body = {
      name: p.name,
      description: p.desc,
      shortDescription: p.short,
      tags: p.tags,
      categoryId: catId,
      brandId: brandMap[p.brandSlug] || undefined,
      gender: p.gender,
      basePrice: p.base,
      salePrice: p.sale,
      sku: p.sku,
      status: 'PUBLISHED',
      isActive: true,
      isFeatured: p.feat,
      isNewArrival: p.newArr,
      isBestSeller: p.best,
      isTrending: p.trend,
      fabric: p.fabric,
      material: p.material,
      washCare: p.wash,
      hsnCode: '6109',
      gstRate: 12,
      returnAvailable: true,
      returnPeriod: 30,
      exchangeAvailable: true,
      warrantyPeriod: 'Standard Quality',
      couponEligible: true,
      flashSale: p.flash,
      festivalOffer: p.fest,
      metaTitle: p.name,
      metaDescription: p.short,
      metaKeywords: p.tags,
      images: imgs(p.sku.toLowerCase(), p.imgCount),
      variants: variants(p.sku, p.sizes, p.colors, p.sale),
    };

    try {
      const res: any = await apiPost('/admin/products', body, token);
      if (res.success) {
        created++;
        if (created % 10 === 0) console.log(`  Created ${created} products...`);
      } else if (res.message && res.message.includes('many requests')) {
        // Rate limited — wait 15s and retry once
        console.log(`  Rate limited on [${p.sku}], waiting 15s...`);
        await new Promise((r) => setTimeout(r, 15000));
        const retry: any = await apiPost('/admin/products', body, token);
        if (retry.success) {
          created++;
          console.log(`  Retry OK: ${p.name}`);
        } else {
          console.log(`  RETRY FAIL [${p.sku}]: ${retry.message || 'unknown'}`);
          failed++;
        }
      } else {
        console.log(`  FAIL [${p.sku}]: ${res.message || 'unknown error'}`);
        failed++;
      }
    } catch (err: any) {
      console.log(`  ERROR [${p.sku}]: ${err.message}`);
      failed++;
    }

    // Delay between requests to avoid rate limiting
    await new Promise((r) => setTimeout(r, 2000));
  }

  console.log(`\n=== DONE ===`);
  console.log(`Created: ${created}`);
  console.log(`Failed: ${failed}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Total attempted: ${products.length}`);
}

main().catch((e) => {
  console.error('FATAL:', e);
  process.exit(1);
});
