import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function imgs(slug: string, count = 7): { url: string; alt: string; isPrimary: boolean; displayOrder: number }[] {
  return Array.from({ length: count }, (_, i) => ({
    url: `https://picsum.photos/seed/${slug}-${i + 1}/600/800`,
    alt: `${slug} image ${i + 1}`,
    isPrimary: i === 0,
    displayOrder: i,
  }));
}

function variants(sku: string, sizes: string[], colors: { name: string; hex: string }[], basePrice: number) {
  const v: { size: string; color: string; colorHex: string; sku: string; price: number; stock: number }[] = [];
  for (const c of colors) {
    for (const s of sizes) {
      v.push({ size: s, color: c.name, colorHex: c.hex, sku: `${sku}-${c.name.toUpperCase().slice(0, 3)}-${s}`, price: basePrice, stock: Math.floor(Math.random() * 40) + 5 });
    }
  }
  return v;
}

const MEN_SIZES = ['S', 'M', 'L', 'XL', 'XXL'];
const WOMEN_SIZES = ['XS', 'S', 'M', 'L', 'XL'];
const KID_SIZES = ['4-5Y', '6-7Y', '8-9Y', '10-11Y', '12-13Y'];
const SHOE_SIZES = ['6', '7', '8', '9', '10'];

const BLACK = { name: 'Black', hex: '#000000' };
const WHITE = { name: 'White', hex: '#FFFFFF' };
const NAVY = { name: 'Navy', hex: '#1a1a2e' };
const RED = { name: 'Red', hex: '#e94560' };
const BLUE = { name: 'Blue', hex: '#2563eb' };
const GREEN = { name: 'Green', hex: '#16a34a' };
const GREY = { name: 'Grey', hex: '#6b7280' };
const MAROON = { name: 'Maroon', hex: '#7f1d1d' };
const BEIGE = { name: 'Beige', hex: '#d4a853' };
const PINK = { name: 'Pink', hex: '#ec4899' };

interface ProductDef {
  name: string;
  description: string;
  shortDescription: string;
  tags: string;
  gender: string;
  basePrice: number;
  salePrice: number;
  sku: string;
  categorySlug: string;
  brandSlug: string;
  fabric: string;
  material: string;
  washCare: string;
  isFeatured: boolean;
  isNewArrival: boolean;
  isBestSeller: boolean;
  isTrending: boolean;
  flashSale: boolean;
  festivalOffer: boolean;
  sizes: string[];
  colors: { name: string; hex: string }[];
  imageCount: number;
}

const products: ProductDef[] = [
  // ==================== MEN - T-SHIRTS (10) ====================
  { name: 'Classic Crew Neck T-Shirt', description: 'A wardrobe essential crafted from 100% combed cotton. This crew neck t-shirt features a regular fit with pre-shrunk fabric that retains its shape wash after wash. Ribbed collar maintains its form, while double-stitched seams ensure durability. The soft hand feel makes it perfect for all-day wear, whether layered under a jacket or worn solo.', shortDescription: 'Premium cotton crew neck with regular fit', tags: 't-shirt,cotton,casual,basics,crew-neck', gender: 'MEN', basePrice: 799, salePrice: 499, sku: 'M-TS-101', categorySlug: 'men-t-shirts', brandSlug: 'premium-wear', fabric: '100% Combed Cotton', material: 'Pure Cotton 180 GSM', washCare: 'Machine wash cold with like colors. Do not bleach. Tumble dry low.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, WHITE, NAVY, GREY], imageCount: 7 },
  { name: 'Slim Fit Polo T-Shirt', description: 'Smart-casual polo shirt in premium pique cotton with a tailored slim fit. Features a classic two-button placket, ribbed collar and cuffs, and side vents for ease of movement. The textured pique weave gives it a refined look suitable for weekend brunches, golf outings, or casual office days.', shortDescription: 'Pique cotton polo with slim fit', tags: 'polo,t-shirt,cotton,smart-casual,slim-fit', gender: 'MEN', basePrice: 1299, salePrice: 899, sku: 'M-TS-102', categorySlug: 'men-t-shirts', brandSlug: 'urban-style', fabric: 'Pique Cotton', material: 'Cotton Blend 200 GSM', washCare: 'Machine wash inside out. Hang dry recommended.', isFeatured: true, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, WHITE, NAVY, RED], imageCount: 7 },
  { name: 'Oversized Graphic Tee - Urban Collection', description: 'Streetwear-inspired oversized t-shirt with bold graphic print on the front. Made from heavyweight 220 GSM cotton with a dropped shoulder silhouette and extended length. The oversized cut delivers a relaxed, contemporary look that pairs perfectly with cargo pants, joggers, or slim jeans.', shortDescription: 'Heavyweight oversized graphic tee', tags: 'graphic-tee,oversized,streetwear,cotton', gender: 'MEN', basePrice: 1499, salePrice: 999, sku: 'M-TS-103', categorySlug: 'men-t-shirts', brandSlug: 'street-vogue', fabric: 'Heavyweight Cotton', material: '100% Cotton 220 GSM', washCare: 'Turn inside out before washing. Cold wash only.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, WHITE, GREY], imageCount: 7 },
  { name: 'Henley Neck T-Shirt', description: 'Versatile henley neck t-shirt with a three-button placket. Made from soft cotton jersey with a relaxed fit. The henley collar adds a touch of rugged sophistication, making it ideal for layering in cooler months or wearing alone in summer.', shortDescription: 'Cotton henley with button placket', tags: 'henley,t-shirt,cotton,layering', gender: 'MEN', basePrice: 999, salePrice: 699, sku: 'M-TS-104', categorySlug: 'men-t-shirts', brandSlug: 'classic-threads', fabric: 'Cotton Jersey', material: '100% Cotton 180 GSM', washCare: 'Machine wash cold. Do not iron on print.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: true, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, NAVY, MAROON, GREY], imageCount: 7 },
  { name: 'V-Neck Solid T-Shirt', description: 'Elegant v-neck t-shirt in smooth cotton jersey. The deeper V-neckline creates a flattering silhouette while the slim-fit cut accentuates the body. Perfect for wearing under blazers or as a standalone piece for a clean, minimalist look.', shortDescription: 'Slim fit v-neck in premium cotton', tags: 'v-neck,t-shirt,cotton,slim-fit,formal', gender: 'MEN', basePrice: 899, salePrice: 599, sku: 'M-TS-105', categorySlug: 'men-t-shirts', brandSlug: 'modern-fit', fabric: 'Cotton Elastane', material: '95% Cotton, 5% Elastane', washCare: 'Machine wash cold with similar colors.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, WHITE, NAVY], imageCount: 7 },
  { name: 'Striped Rugby T-Shirt', description: 'Classic rugby-style t-shirt with bold horizontal stripes and a reinforced collar. Made from durable cotton jersey with contrast tape at the placket. A heritage sportswear piece that brings vintage charm to modern casual wardrobes.', shortDescription: 'Rugby style striped t-shirt', tags: 'rugby,striped,t-shirt,casual,vintage', gender: 'MEN', basePrice: 1399, salePrice: 999, sku: 'M-TS-106', categorySlug: 'men-t-shirts', brandSlug: 'premium-wear', fabric: 'Cotton Jersey', material: '100% Cotton 200 GSM', washCare: 'Machine wash cold. Wash inside out.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: true, sizes: MEN_SIZES, colors: [NAVY, RED, GREEN], imageCount: 7 },
  { name: 'Longline T-Shirt', description: 'Contemporary longline t-shirt with an extended hem and side slits. Made from premium cotton with a relaxed drape. The longer length provides extra coverage and a modern streetwear aesthetic. Pairs well with skinny jeans or joggers.', shortDescription: 'Extended hem longline tee', tags: 'longline,t-shirt,streetwear,modern', gender: 'MEN', basePrice: 1099, salePrice: 799, sku: 'M-TS-107', categorySlug: 'men-t-shirts', brandSlug: 'street-vogue', fabric: 'Cotton', material: '100% Cotton 190 GSM', washCare: 'Machine wash cold. Hang dry.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, WHITE, GREY], imageCount: 7 },
  { name: 'Performance Dry-Fit T-Shirt', description: 'Engineered for active lifestyles with moisture-wicking Dri-FIT technology. Lightweight and breathable with mesh ventilation panels. Four-way stretch fabric allows unrestricted movement. Ideal for gym sessions, running, and outdoor sports.', shortDescription: 'Moisture-wicking sports tee', tags: 'activewear,sports,dry-fit,gym,running', gender: 'MEN', basePrice: 1199, salePrice: 799, sku: 'M-TS-108', categorySlug: 'men-t-shirts', brandSlug: 'elite-collection', fabric: 'Polyester Spandex', material: '92% Polyester, 8% Spandex', washCare: 'Machine wash cold. Do not use fabric softener.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, NAVY, RED, GREEN], imageCount: 7 },
  { name: 'Linen Blend Vacation Tee', description: 'Relaxed-fit t-shirt in a breathable linen-cotton blend. The natural texture of linen gives it a laid-back vacation vibe while the cotton content ensures softness against the skin. Perfect for beach days and summer getaways.', shortDescription: 'Linen blend relaxed tee', tags: 'linen,summer,vacation,casual,blend', gender: 'MEN', basePrice: 1299, salePrice: 899, sku: 'M-TS-109', categorySlug: 'men-t-shirts', brandSlug: 'classic-threads', fabric: 'Linen Cotton Blend', material: '55% Linen, 45% Cotton', washCare: 'Hand wash recommended. Do not bleach.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [WHITE, BEIGE, NAVY], imageCount: 7 },
  { name: 'Zip-Up Hoodie T-Shirt', description: 'Hybrid zip-up t-shirt with a lightweight terry fabric and full-zip front. Features raglan sleeves for enhanced mobility and a stand collar. Works as a layering piece in transitional weather or as a standalone top.', shortDescription: 'Lightweight zip-up terry top', tags: 'zip-up,hoodie,layering,terry', gender: 'MEN', basePrice: 1599, salePrice: 1099, sku: 'M-TS-110', categorySlug: 'men-t-shirts', brandSlug: 'urban-style', fabric: 'French Terry', material: '80% Cotton, 20% Polyester', washCare: 'Machine wash cold. Zip before washing.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: true, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, GREY, NAVY], imageCount: 7 },

  // ==================== MEN - SHIRTS (8) ====================
  { name: 'Classic Oxford Button-Down', description: 'Timeless Oxford cloth button-down shirt with a tailored fit. Features a button-down collar, single chest pocket, and adjustable barrel cuffs. The Oxford weave provides a subtle texture that bridges casual and smart effortlessly. A foundation piece for any well-dressed man\'s wardrobe.', shortDescription: 'Oxford cotton button-down shirt', tags: 'shirt,oxford,cotton,formal,smart-casual', gender: 'MEN', basePrice: 2299, salePrice: 1599, sku: 'M-SH-201', categorySlug: 'men-shirts', brandSlug: 'classic-threads', fabric: 'Oxford Cotton', material: '100% Cotton 140 GSM', washCare: 'Machine wash warm. Iron while slightly damp.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [WHITE, BLUE, NAVY, PINK], imageCount: 8 },
  { name: 'Slim Fit Linen Shirt', description: 'Breathable linen shirt with a modern slim fit. Features a spread collar, front patch pocket, and mitered cuffs. The natural slubs in the linen fabric create an effortlessly stylish texture. Ideal for summer weddings, garden parties, and upscale casual events.', shortDescription: 'Slim fit linen shirt for summer', tags: 'linen,shirt,summer,slim-fit,formal', gender: 'MEN', basePrice: 2799, salePrice: 1999, sku: 'M-SH-202', categorySlug: 'men-shirts', brandSlug: 'premium-wear', fabric: '100% Linen', material: 'Pure Linen 150 GSM', washCare: 'Hand wash cold or gentle machine wash. Hang dry.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [WHITE, BEIGE, LIGHT_BLUE, GREEN], imageCount: 7 },
  { name: 'Flannel Check Shirt', description: 'Warm and cozy flannel shirt in a classic plaid pattern. Made from brushed cotton flannel that gets softer with each wash. Features a relaxed fit, button-down collar, and chest pockets. The perfect layering piece for fall and winter.', shortDescription: 'Brushed flannel plaid shirt', tags: 'flannel,check,winter,casual,plaid', gender: 'MEN', basePrice: 2499, salePrice: 1799, sku: 'M-SH-203', categorySlug: 'men-shirts', brandSlug: 'urban-style', fabric: 'Brushed Flannel', material: '100% Cotton Flannel 160 GSM', washCare: 'Machine wash warm with like colors.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: true, sizes: MEN_SIZES, colors: [RED, NAVY, GREEN, GREY], imageCount: 7 },
  { name: 'Formal Spread Collar Shirt', description: 'Impeccably tailored formal shirt in premium cotton poplin. Features a wide spread collar compatible with all tie knot styles, a French placket for a clean front, and adjustable cuff links. Wrinkle-resistant finish ensures a polished look throughout the workday.', shortDescription: 'Premium cotton formal shirt', tags: 'formal,shirt,cotton,office,tie', gender: 'MEN', basePrice: 2999, salePrice: 2199, sku: 'M-SH-204', categorySlug: 'men-shirts', brandSlug: 'elite-collection', fabric: 'Cotton Poplin', material: '100% Egyptian Cotton', washCare: 'Dry clean recommended. Iron on medium heat.', isFeatured: true, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [WHITE, BLUE, PINK, LAVENDER], imageCount: 7 },
  { name: 'Denim Western Shirt', description: 'Rugged denim shirt with authentic Western detailing. Features snap-button front, twin chest pockets with snap flaps, and curved hem. Made from soft washed denim that\'s comfortable from day one. A versatile layering piece that works open over a tee or buttoned up.', shortDescription: 'Western style denim shirt', tags: 'denim,western,shirt,casual,rugged', gender: 'MEN', basePrice: 2699, salePrice: 1899, sku: 'M-SH-205', categorySlug: 'men-shirts', brandSlug: 'street-vogue', fabric: 'Denim', material: '100% Cotton Denim 12oz', washCare: 'Wash inside out in cold water. Hang dry.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLUE, BLACK, GREY], imageCount: 7 },
  { name: 'Camp Collar Resort Shirt', description: 'Relaxed camp collar shirt inspired by vintage resort wear. Features an open collar, boxy fit, and a straight hem designed to be worn untucked. Made from lightweight viscose with a tropical print that brings vacation vibes wherever you go.', shortDescription: 'Camp collar resort shirt', tags: 'camp-collar,resort,summer,vacation,printed', gender: 'MEN', basePrice: 1899, salePrice: 1399, sku: 'M-SH-206', categorySlug: 'men-shirts', brandSlug: 'modern-fit', fabric: 'Viscose', material: '100% Viscose', washCare: 'Hand wash cold. Do not wring.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [GREEN, BLUE, BEIGE], imageCount: 7 },
  { name: 'Striped Regular Fit Shirt', description: 'Classic striped shirt with a comfortable regular fit. Features a straight collar, full button front, and a single chest pocket. The timeless vertical stripes create a slimming effect while the cotton-rich fabric keeps you comfortable all day.', shortDescription: 'Regular fit striped cotton shirt', tags: 'striped,shirt,cotton,regular-fit', gender: 'MEN', basePrice: 1999, salePrice: 1399, sku: 'M-SH-207', categorySlug: 'men-shirts', brandSlug: 'classic-threads', fabric: 'Cotton Blend', material: '80% Cotton, 20% Polyester', washCare: 'Machine wash cold. Tumble dry low.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: true, festivalOffer: false, sizes: MEN_SIZES, colors: [WHITE, BLUE, NAVY], imageCount: 7 },
  { name: 'Corduroy Overshirt', description: 'Heavyweight corduroy overshirt that bridges the gap between shirt and jacket. Features a spread collar, button front, and chest pockets. The rich corduroy texture adds depth and warmth. Perfect as a layering piece over tees and hoodies in cooler weather.', shortDescription: 'Corduroy overshirt layering piece', tags: 'corduroy,overshirt,layering,autumn,winter', gender: 'MEN', basePrice: 3499, salePrice: 2499, sku: 'M-SH-208', categorySlug: 'men-shirts', brandSlug: 'elite-collection', fabric: 'Corduroy', material: '100% Cotton Corduroy', washCare: 'Machine wash cold inside out.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [NAVY, BROWN, GREEN], imageCount: 7 },

  // ==================== MEN - JEANS (7) ====================
  { name: 'Slim Fit Stretch Jeans', description: 'Modern slim fit jeans with 4-way stretch denim for unrestricted movement. Mid-rise waist with a tapered leg that hits right at the ankle. Features classic five-pocket styling with reinforced rivets. The advanced stretch recovery technology ensures these jeans retain their shape throughout the day.', shortDescription: '4-way stretch slim fit jeans', tags: 'jeans,slim-fit,stretch,denim', gender: 'MEN', basePrice: 2999, salePrice: 1999, sku: 'M-JN-301', categorySlug: 'men-jeans', brandSlug: 'modern-fit', fabric: 'Stretch Denim', material: '98% Cotton, 2% Elastane', washCare: 'Machine wash cold inside out. Do not bleach.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLUE, BLACK, GREY], imageCount: 7 },
  { name: 'Regular Fit Classic Indigo', description: 'Timeless regular fit jeans in authentic indigo wash. Made from 12oz rigid denim that develops a unique patina over time. Straight leg with a comfortable mid-rise. A heritage denim piece that only gets better with age.', shortDescription: 'Classic indigo regular fit jeans', tags: 'jeans,regular-fit,indigo,classic,rigid', gender: 'MEN', basePrice: 2499, salePrice: 1799, sku: 'M-JN-302', categorySlug: 'men-jeans', brandSlug: 'classic-threads', fabric: 'Rigid Denim', material: '100% Cotton Denim 12oz', washCare: 'Wash sparingly. Cold water only. Hang dry.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLUE, DARK_BLUE], imageCount: 7 },
  { name: 'Skinny Fit Black Jeans', description: 'Sleek skinny fit jeans in a jet-black wash with subtle fade details. Super-stretch fabric provides a body-hugging fit without compromising comfort. Low-rise waist with an ankle-length hem. A must-have for rock-inspired and contemporary looks.', shortDescription: 'Jet black skinny jeans', tags: 'jeans,skinny,black,stretch', gender: 'MEN', basePrice: 2799, salePrice: 1899, sku: 'M-JN-303', categorySlug: 'men-jeans', brandSlug: 'street-vogue', fabric: 'Stretch Denim', material: '97% Cotton, 3% Elastane', washCare: 'Wash inside out in cold water with dark colors.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, DARK_GREY], imageCount: 7 },
  { name: 'Relaxed Fit Cargo Jeans', description: 'Utilitarian cargo jeans with a relaxed fit and multiple pockets. Features side cargo pockets with button flaps, back welt pockets, and a tapered leg. Made from durable cotton twill with a vintage wash. Blends workwear heritage with modern streetwear sensibility.', shortDescription: 'Cargo style relaxed fit jeans', tags: 'cargo,jeans,relaxed,utility,streetwear', gender: 'MEN', basePrice: 3299, salePrice: 2299, sku: 'M-JN-304', categorySlug: 'men-jeans', brandSlug: 'street-vogue', fabric: 'Cotton Twill', material: '100% Cotton', washCare: 'Machine wash cold with like colors.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [GREEN, BLACK, BEIGE], imageCount: 7 },
  { name: 'Tapered Fit Acid Wash Jeans', description: 'Statement acid wash jeans with a modern tapered fit. Features a mid-rise waist, five-pocket styling, and a tapered leg that narrows toward the ankle. The bold acid wash pattern creates a retro 80s vibe with contemporary proportions.', shortDescription: 'Acid wash tapered jeans', tags: 'jeans,tapered,acid-wash,retro', gender: 'MEN', basePrice: 2699, salePrice: 1899, sku: 'M-JN-305', categorySlug: 'men-jeans', brandSlug: 'urban-style', fabric: 'Denim', material: '100% Cotton Denim', washCare: 'Wash inside out. Cold water. Separate from light colors.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLUE, BLACK], imageCount: 7 },
  { name: 'High Rise Straight Jeans', description: 'Vintage-inspired high rise jeans with a straight leg silhouette. Made from non-stretch rigid denim for an authentic retro feel. Features a button fly, copper rivets, and a raw hem option. A throwback to classic American denim craftsmanship.', shortDescription: 'High rise straight leg jeans', tags: 'jeans,high-rise,straight,vintage,rigid', gender: 'MEN', basePrice: 2899, salePrice: 2099, sku: 'M-JN-306', categorySlug: 'men-jeans', brandSlug: 'premium-wear', fabric: 'Rigid Denim', material: '100% Cotton Denim 14oz', washCare: 'Dry clean preferred. Wash inside out when needed.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: true, festivalOffer: false, sizes: MEN_SIZES, colors: [BLUE, BLACK], imageCount: 7 },
  { name: 'Distressed Boyfriend Jeans', description: 'Relaxed boyfriend jeans with intentional distressing and ripped details. Features a low-to-mid rise, relaxed through the hip and thigh, and a tapered leg. The pre-worn look gives these jeans instant character and a lived-in feel.', shortDescription: 'Distressed boyfriend fit jeans', tags: 'jeans,boyfriend,distressed,ripped,casual', gender: 'MEN', basePrice: 2599, salePrice: 1799, sku: 'M-JN-307', categorySlug: 'men-jeans', brandSlug: 'urban-style', fabric: 'Denim', material: '99% Cotton, 1% Elastane', washCare: 'Machine wash cold. Do not iron on distressed areas.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: true, sizes: MEN_SIZES, colors: [BLUE, LIGHT_BLUE, BLACK], imageCount: 7 },

  // ==================== MEN - JACKETS & OUTERWEAR (7) ====================
  { name: 'Classic Bomber Jacket', description: 'Iconic bomber jacket with a regular fit and lightweight quilted lining. Features a zip front, rib-knit collar/cuffs/hem, and slanted side pockets. The water-resistant shell makes it practical for light rain while the classic silhouette ensures timeless appeal.', shortDescription: 'Quilted bomber with zip closure', tags: 'bomber,jacket,outerwear,casual,classic', gender: 'MEN', basePrice: 4999, salePrice: 3499, sku: 'M-JK-401', categorySlug: 'men-jackets', brandSlug: 'premium-wear', fabric: 'Nylon Polyester', material: '100% Polyester Shell, Polyester Fill', washCare: 'Machine wash cold on gentle cycle.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, NAVY, OLIVE], imageCount: 7 },
  { name: 'Premium Leather Biker Jacket', description: 'Luxurious genuine leather biker jacket with an asymmetric zip closure. Features notch lapels with silver snap buttons, quilted shoulder panels, and multiple zip pockets. Fully lined in satin for comfort. A statement piece that only gets better with age.', shortDescription: 'Genuine leather biker jacket', tags: 'leather,biker,jacket,premium,luxury', gender: 'MEN', basePrice: 14999, salePrice: 10999, sku: 'M-JK-402', categorySlug: 'men-jackets', brandSlug: 'elite-collection', fabric: 'Genuine Leather', material: '100% Sheep Leather', washCare: 'Professional leather clean only. Condition regularly.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, BROWN], imageCount: 8 },
  { name: 'Denim Trucker Jacket', description: 'Classic trucker jacket in medium-wash denim. Features a button front, chest pockets with button flaps, and adjustable waist tabs. The versatile mid-weight denim makes it a perfect layering piece across all seasons.', shortDescription: 'Classic denim trucker jacket', tags: 'denim,trucker,jacket,classic,layering', gender: 'MEN', basePrice: 3999, salePrice: 2799, sku: 'M-JK-403', categorySlug: 'men-jackets', brandSlug: 'classic-threads', fabric: 'Denim', material: '100% Cotton Denim', washCare: 'Wash inside out in cold water.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: true, sizes: MEN_SIZES, colors: [BLUE, BLACK], imageCount: 7 },
  { name: 'Puffer Jacket - Winter Edition', description: 'Insulated puffer jacket with responsibly sourced down fill for superior warmth without bulk. Features a water-resistant shell, zip front with storm flap, and elasticated cuffs. Packs down into its own pocket for easy travel.', shortDescription: 'Insulated down puffer jacket', tags: 'puffer,jacket,winter,down,insulated', gender: 'MEN', basePrice: 5999, salePrice: 4199, sku: 'M-JK-404', categorySlug: 'men-jackets', brandSlug: 'elite-collection', fabric: 'Recycled Nylon', material: '100% Recycled Nylon, 700-fill Down', washCare: 'Machine wash cold on gentle. Tumble dry low with tennis balls.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, NAVY, OLIVE], imageCount: 7 },
  { name: 'Windbreaker Rain Jacket', description: 'Lightweight packable windbreaker with sealed seams for waterproof protection. Features a hood, ventilation back panel, and reflective details for visibility. Weighs under 300g making it the perfect travel companion.', shortDescription: 'Packable waterproof windbreaker', tags: 'windbreaker,rain,waterproof,lightweight,travel', gender: 'MEN', basePrice: 3499, salePrice: 2499, sku: 'M-JK-405', categorySlug: 'men-jackets', brandSlug: 'urban-style', fabric: 'Ripstop Nylon', material: '100% Nylon with DWR coating', washCare: 'Machine wash cold. Re-activate DWR with low heat tumble dry.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: true, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, BLUE, RED], imageCount: 7 },
  { name: 'Varsity Baseball Jacket', description: 'Collegiate-inspired varsity jacket with a wool-blend body and faux leather sleeves. Features rib-knit collar, cuffs, and hem with snap-button closure. Embroidered patches add authentic athletic detailing.', shortDescription: 'Varsity baseball jacket', tags: 'varsity,baseball,jacket,collegiate,retro', gender: 'MEN', basePrice: 4499, salePrice: 3199, sku: 'M-JK-406', categorySlug: 'men-jackets', brandSlug: 'street-vogue', fabric: 'Wool Blend', material: '80% Wool, 20% Polyester, Faux Leather Sleeves', washCare: 'Dry clean only.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [NAVY, BLACK, GREEN], imageCount: 7 },
  { name: 'Cotton Zip-Up Sweatshirt', description: 'Minimalist cotton sweatshirt with a full-zip front. Made from brushed fleece cotton with a stand collar and ribbed cuffs. A versatile mid-layer that works equally well as outerwear on cool evenings.', shortDescription: 'Cotton fleece zip-up sweatshirt', tags: 'sweatshirt,zip-up,cotton,fleece,layering', gender: 'MEN', basePrice: 2999, salePrice: 2099, sku: 'M-JK-407', categorySlug: 'men-jackets', brandSlug: 'modern-fit', fabric: 'Brushed Fleece', material: '80% Cotton, 20% Polyester', washCare: 'Machine wash cold. Tumble dry low.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [GREY, BLACK, NAVY], imageCount: 7 },

  // ==================== MEN - HOODIES & SWEATSHIRTS (5) ====================
  { name: 'Classic Pullover Hoodie', description: 'Essential pullover hoodie in premium cotton fleece. Features a kangaroo pocket, drawstring hood, and ribbed cuffs and hem. The brushed interior provides exceptional warmth and softness. A year-round wardrobe staple.', shortDescription: 'Premium cotton pullover hoodie', tags: 'hoodie,pullover,cotton,comfort,casual', gender: 'MEN', basePrice: 2499, salePrice: 1699, sku: 'M-HD-501', categorySlug: 'men-hoodies', brandSlug: 'premium-wear', fabric: 'Cotton Fleece', material: '80% Cotton, 20% Polyester 320 GSM', washCare: 'Machine wash cold inside out. Tumble dry low.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, GREY, NAVY, MAROON], imageCount: 7 },
  { name: 'Oversized Drop-Shoulder Hoodie', description: 'Trendy oversized hoodie with a dropped shoulder seam and extended body length. Made from heavyweight French terry for a structured drape. Features a double-lined hood and kangaroo pocket. The exaggerated proportions create a bold streetwear silhouette.', shortDescription: 'Oversized hoodie with drop shoulders', tags: 'hoodie,oversized,streetwear,french-terry', gender: 'MEN', basePrice: 2999, salePrice: 2099, sku: 'M-HD-502', categorySlug: 'men-hoodies', brandSlug: 'street-vogue', fabric: 'French Terry', material: '100% Cotton 380 GSM', washCare: 'Machine wash cold. Do not iron on print.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, WHITE, GREY, OLIVE], imageCount: 7 },
  { name: 'Zip-Through Tech Hoodie', description: 'Performance hoodie with a full-zip front and technical fabric. Features moisture-wicking properties, quick-dry technology, and zippered side pockets. The streamlined design works for both workouts and casual outings.', shortDescription: 'Tech fabric zip-up hoodie', tags: 'hoodie,tech,zip-through,performance,activewear', gender: 'MEN', basePrice: 3499, salePrice: 2499, sku: 'M-HD-503', categorySlug: 'men-hoodies', brandSlug: 'elite-collection', fabric: 'Tech Fleece', material: '100% Polyester', washCare: 'Machine wash cold. Do not use fabric softener.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: MEN_SIZES, colors: [BLACK, NAVY, GREY], imageCount: 7 },
  { name: 'Striped Colorblock Hoodie', description: 'Bold colorblock hoodie with contrasting stripes and panels. Made from medium-weight cotton fleece with a relaxed fit. Features a graphic front print, kangaroo pocket, and adjustable drawstring hood. A statement piece for streetwear enthusiasts.', shortDescription: 'Colorblock striped hoodie', tags: 'hoodie,colorblock,striped,streetwear,bold', gender: 'MEN', basePrice: 2799, salePrice: 1999, sku: 'M-HD-504', categorySlug: 'men-hoodies', brandSlug: 'street-vogue', fabric: 'Cotton Fleece', material: '80% Cotton, 20% Polyester', washCare: 'Machine wash cold inside out with like colors.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: true, sizes: MEN_SIZES, colors: [BLACK, GREY, NAVY], imageCount: 7 },
  { name: 'Waffle Knit Hoodie', description: 'Textured waffle knit hoodie with a relaxed fit and cozy warmth. Features a three-panel hood, kangaroo pocket, and ribbed trims. The waffle texture adds visual interest while the cotton-blend fabric provides all-day comfort.', shortDescription: 'Waffle knit texture hoodie', tags: 'hoodie,waffle-knit,textured,comfort', gender: 'MEN', basePrice: 2699, salePrice: 1899, sku: 'M-HD-505', categorySlug: 'men-hoodies', brandSlug: 'classic-threads', fabric: 'Waffle Knit', material: '70% Cotton, 30% Polyester', washCare: 'Machine wash cold on gentle cycle.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: true, festivalOffer: false, sizes: MEN_SIZES, colors: [BEIGE, GREY, BLACK], imageCount: 7 },

  // ==================== WOMEN - DRESSES (8) ====================
  { name: 'Floral Wrap Dress', description: 'Flattering wrap dress with a vibrant all-over floral print. Made from lightweight viscose with a flowing drape. Features a V-neckline, short flutter sleeves, and a tie waist that accentuates the figure. Perfect for brunch dates, garden parties, and summer events.', shortDescription: 'Floral print viscose wrap dress', tags: 'dress,wrap,floral,summer,viscose', gender: 'WOMEN', basePrice: 2999, salePrice: 1999, sku: 'W-DR-601', categorySlug: 'women-dresses', brandSlug: 'premium-wear', fabric: 'Viscose', material: '100% Viscose', washCare: 'Hand wash cold or gentle machine wash.', isFeatured: true, isNewArrival: true, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [RED, BLUE, GREEN], imageCount: 7 },
  { name: 'Little Black Dress - Party Edit', description: 'Timeless little black dress with a modern twist. Features a fitted bodice, sweetheart neckline, and a flared mini skirt. Made from premium crepe with a slight stretch for a flattering fit. The perfect canvas for statement jewelry and heels.', shortDescription: 'Classic LBD in premium crepe', tags: 'dress,party,black,cocktail,classic', gender: 'WOMEN', basePrice: 3999, salePrice: 2799, sku: 'W-DR-602', categorySlug: 'women-dresses', brandSlug: 'elite-collection', fabric: 'Crepe', material: '95% Polyester, 5% Spandex', washCare: 'Dry clean recommended. Steam to remove wrinkles.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK], imageCount: 7 },
  { name: 'Tiered Maxi Dress', description: 'Romantic tiered maxi dress in soft georgette. Features adjustable spaghetti straps, a smocked bodice, and three flowing tiers. The floor-length silhouette creates an ethereal look perfect for beach weddings and summer soirées.', shortDescription: 'Tiered georgette maxi dress', tags: 'dress,maxi,tiered,georgette,bohemian', gender: 'WOMEN', basePrice: 3499, salePrice: 2499, sku: 'W-DR-603', categorySlug: 'women-dresses', brandSlug: 'urban-style', fabric: 'Georgette', material: '100% Georgette', washCare: 'Hand wash cold. Do not wring. Hang dry in shade.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, PINK, BLUE], imageCount: 7 },
  { name: 'Bodycon Ruched Dress', description: 'Figure-hugging bodycon dress with ruching detail along the sides. The strategic ruching creates a flattering gathered effect that camouflages while the stretch fabric hugs every curve. Made from jersey with excellent recovery.', shortDescription: 'Bodycon dress with side ruching', tags: 'dress,bodycon,ruched,party,sexy', gender: 'WOMEN', basePrice: 2499, salePrice: 1799, sku: 'W-DR-604', categorySlug: 'women-dresses', brandSlug: 'street-vogue', fabric: 'Jersey', material: '92% Viscose, 8% Elastane', washCare: 'Machine wash cold on delicate cycle.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK, RED, NAVY], imageCount: 7 },
  { name: 'Shirt Dress - Office Edit', description: 'Polished shirt dress with a belted waist and button-through front. Made from crisp cotton poplin with a structured collar and cuffed sleeves. The midi length and tailored fit make it appropriate for the office while remaining effortlessly stylish.', shortDescription: 'Cotton shirt dress with belt', tags: 'dress,shirt,formal,office,cotton', gender: 'WOMEN', basePrice: 3299, salePrice: 2299, sku: 'W-DR-605', categorySlug: 'women-dresses', brandSlug: 'classic-threads', fabric: 'Cotton Poplin', material: '100% Cotton', washCare: 'Machine wash cold. Iron on medium heat.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: true, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, BLUE, NAVY], imageCount: 7 },
  { name: 'Satin Slip Dress', description: 'Luxurious satin slip dress with delicate spaghetti straps and a bias cut that drapes beautifully. The cowl neckline adds a touch of glamour while the side slit allows ease of movement. Can be worn solo or layered over a turtleneck.', shortDescription: 'Satin bias-cut slip dress', tags: 'dress,satin,slip,evening,luxury', gender: 'WOMEN', basePrice: 2799, salePrice: 1999, sku: 'W-DR-606', categorySlug: 'women-dresses', brandSlug: 'elite-collection', fabric: 'Satin', material: '100% Polyester Satin', washCare: 'Hand wash cold in mild detergent. Hang dry.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK, GREEN, BEIGE], imageCount: 7 },
  { name: 'Boho Midi Dress', description: 'Free-spirited bohemian midi dress with paisley print and tiered skirt. Features a V-neckline, bell sleeves, and tassel tie details. Made from soft rayon with a flowing silhouette. Perfect for festivals, vacations, and outdoor events.', shortDescription: 'Paisley boho midi dress', tags: 'dress,boho,bohemian,paisley,midi', gender: 'WOMEN', basePrice: 2699, salePrice: 1899, sku: 'W-DR-607', categorySlug: 'women-dresses', brandSlug: 'street-vogue', fabric: 'Rayon', material: '100% Rayon', washCare: 'Hand wash cold. Do not bleach.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: true, sizes: WOMEN_SIZES, colors: [MULTI, BLUE, RED], imageCount: 7 },
  { name: 'A-Line Midi Dress', description: 'Classic A-line midi dress with a fitted bodice and flared skirt. Made from structured crepe that holds its shape. Features a round neckline, cap sleeves, and concealed back zip. A versatile dress that transitions from office to evening.', shortDescription: 'A-line crepe midi dress', tags: 'dress,a-line,midi,crepe,versatile', gender: 'WOMEN', basePrice: 3199, salePrice: 2199, sku: 'W-DR-608', categorySlug: 'women-dresses', brandSlug: 'modern-fit', fabric: 'Crepe', material: '95% Polyester, 5% Spandex', washCare: 'Machine wash cold on gentle. Hang dry.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK, NAVY, MAROON], imageCount: 7 },

  // ==================== WOMEN - KURTIS (7) ====================
  { name: 'Anarkali Floor-Length Kurti', description: 'Graceful Anarkali kurti with a flared floor-length hemline. Made from luxurious rayon with intricate foil printing. Features a round neckline with golden piping, three-quarter sleeves, and a fitted bodice that flares into a voluminous skirt. Perfect for festivals and special occasions.', shortDescription: 'Floor-length Anarkali kurti', tags: 'kurti,anarkali,festive,rayon,elegant', gender: 'WOMEN', basePrice: 2999, salePrice: 2099, sku: 'W-KU-701', categorySlug: 'women-kurtis', brandSlug: 'premium-wear', fabric: 'Rayon', material: '100% Rayon', washCare: 'Hand wash cold. Dry in shade. Low iron.', isFeatured: true, isNewArrival: true, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: true, sizes: WOMEN_SIZES, colors: [NAVY, MAROON, GREEN], imageCount: 7 },
  { name: 'Cotton Straight-Cut Kurti', description: 'Everyday cotton kurti with a straight-cut silhouette and three-quarter sleeves. Features a mandarin collar with button placket and side slits for ease of movement. The breathable cotton fabric makes it ideal for daily wear and office settings.', shortDescription: 'Cotton straight-cut daily kurti', tags: 'kurti,cotton,straight,daily-wear,office', gender: 'WOMEN', basePrice: 1499, salePrice: 999, sku: 'W-KU-702', categorySlug: 'women-kurtis', brandSlug: 'classic-threads', fabric: 'Cotton', material: '100% Cotton', washCare: 'Machine wash cold. Tumble dry low.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, BLUE, GREEN, PINK], imageCount: 7 },
  { name: 'Printed A-Line Kurti', description: 'Vibrant A-line kurti with an all-over block print design. Made from soft cotton with a flared hemline that creates a feminine silhouette. Features a V-neckline with tassel detail and three-quarter bell sleeves.', shortDescription: 'Block print A-line kurti', tags: 'kurti,a-line,printed,block-print,cotton', gender: 'WOMEN', basePrice: 1799, salePrice: 1299, sku: 'W-KU-703', categorySlug: 'women-kurtis', brandSlug: 'urban-style', fabric: 'Cotton', material: '100% Cotton', washCare: 'Hand wash in cold water. Dry in shade.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLUE, RED, GREEN], imageCount: 7 },
  { name: 'Sharara Set Kurti', description: 'Contemporary sharara set featuring a short kurti paired with flared sharara pants. Made from georgette with sequin embellishments and scalloped edges. A modern take on traditional Indian wear, perfect for sangeet and festive celebrations.', shortDescription: 'Georgette sharara set with kurti', tags: 'kurti,sharara,set,georgette,festive,party', gender: 'WOMEN', basePrice: 4999, salePrice: 3499, sku: 'W-KU-704', categorySlug: 'women-kurtis', brandSlug: 'elite-collection', fabric: 'Georgette', material: '100% Georgette with Sequin Work', washCare: 'Dry clean only. Store in garment bag.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [MAROON, NAVY, GREEN], imageCount: 7 },
  { name: 'Indigo Dye Kurti', description: 'Hand-dyed indigo kurti with traditional Bandhani pattern. Made from pure cotton with an artisanal finish that makes each piece unique. Features a round neckline, three-quarter sleeves, and a straight hem. Celebrates Indian craftsmanship.', shortDescription: 'Hand-dyed indigo Bandhani kurti', tags: 'kurti,indigo,bandhani,handmade,artisan', gender: 'WOMEN', basePrice: 2299, salePrice: 1699, sku: 'W-KU-705', categorySlug: 'women-kurtis', brandSlug: 'classic-threads', fabric: 'Cotton', material: '100% Handloom Cotton', washCare: 'Hand wash separately in cold water first 3 washes.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLUE, NAVY], imageCount: 7 },
  { name: 'Embroidered Kurta Set', description: 'Elegant kurta set with a long kurta and matching palazzo pants. Features intricate thread embroidery on the neckline and hem. Made from soft rayon with a relaxed fit. A complete outfit for festive gatherings and cultural events.', shortDescription: 'Embroidered kurta with palazzo', tags: 'kurti,kurta,set,palazzo,embroidered,festive', gender: 'WOMEN', basePrice: 3499, salePrice: 2499, sku: 'W-KU-706', categorySlug: 'women-kurtis', brandSlug: 'premium-wear', fabric: 'Rayon', material: '100% Rayon with Thread Embroidery', washCare: 'Hand wash cold. Dry in shade.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: true, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK, MAROON, GREEN], imageCount: 7 },
  { name: 'Cape Style Kurti', description: 'Statement cape-style kurti with an attached cape overlay that creates dramatic movement. Made from flowing georgette with a solid inner lining. The cape adds a contemporary edge to the traditional kurti silhouette.', shortDescription: 'Cape overlay georgette kurti', tags: 'kurti,cape,georgette,contemporary,dramatic', gender: 'WOMEN', basePrice: 2799, salePrice: 1999, sku: 'W-KU-707', categorySlug: 'women-kurtis', brandSlug: 'modern-fit', fabric: 'Georgette', material: '100% Georgette with Satin Lining', washCare: 'Dry clean recommended. Hand wash gentle.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK, NAVY, BEIGE], imageCount: 7 },

  // ==================== WOMEN - TOPS (7) ====================
  { name: 'Ruched Crop Top', description: 'Trendy ruched crop top with adjustable side drawstrings. Made from ribbed knit fabric with a body-hugging fit. Features a square neckline and cap sleeves. The ruching detail adds texture while the cropped length pairs perfectly with high-waisted bottoms.', shortDescription: 'Ribbed ruched crop top', tags: 'top,crop,ruched,ribbed,trendy', gender: 'WOMEN', basePrice: 999, salePrice: 699, sku: 'W-TP-801', categorySlug: 'women-tops', brandSlug: 'street-vogue', fabric: 'Ribbed Knit', material: '95% Viscose, 5% Elastane', washCare: 'Machine wash cold on delicate cycle.', isFeatured: false, isNewArrival: true, isBestSeller: true, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK, WHITE, PINK, GREEN], imageCount: 7 },
  { name: 'Peplum Blouse', description: 'Feminine peplum blouse with a fitted bodice and flared peplum waist. Made from structured crepe with a flattering V-neckline and three-quarter sleeves. The peplum detail cinches the waist while the flare creates an hourglass silhouette.', shortDescription: 'Crepe peplum blouse', tags: 'top,peplum,blouse,feminine,office', gender: 'WOMEN', basePrice: 1699, salePrice: 1199, sku: 'W-TP-802', categorySlug: 'women-tops', brandSlug: 'elite-collection', fabric: 'Crepe', material: '95% Polyester, 5% Spandex', washCare: 'Machine wash cold. Hang dry. Low iron.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, BLACK, NAVY], imageCount: 7 },
  { name: 'Oversized Graphic Tee', description: 'Relaxed oversized tee with a bold front graphic. Made from heavyweight cotton with a dropped shoulder silhouette. The boxy fit and extended length create a laid-back streetwear aesthetic. Pairs well with bike shorts or skinny jeans.', shortDescription: 'Oversized graphic cotton tee', tags: 'top,t-shirt,oversized,graphic,streetwear', gender: 'WOMEN', basePrice: 1299, salePrice: 899, sku: 'W-TP-803', categorySlug: 'women-tops', brandSlug: 'street-vogue', fabric: 'Cotton', material: '100% Cotton 200 GSM', washCare: 'Turn inside out before washing. Cold wash.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, BLACK, GREY], imageCount: 7 },
  { name: 'Organza Puff Sleeve Top', description: 'Statement organza top with dramatic puff sleeves and a fitted bodice. The sheer organza sleeves create a romantic, editorial look while the solid lining ensures coverage. Features a sweetheart neckline with subtle gathered detailing.', shortDescription: 'Organza puff sleeve top', tags: 'top,organza,puff-sleeve,romantic,statement', gender: 'WOMEN', basePrice: 1899, salePrice: 1399, sku: 'W-TP-804', categorySlug: 'women-tops', brandSlug: 'premium-wear', fabric: 'Organza', material: '100% Polyester Organza', washCare: 'Hand wash cold. Do not wring. Steam gently.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, PINK, BLACK], imageCount: 7 },
  { name: 'Linen Summer Top', description: 'Breezy linen top with a relaxed fit and camp collar. Made from pure linen that gets softer with each wash. Features a boxy cut with side slits for maximum airflow. The perfect warm-weather top for casual outings and beach vacations.', shortDescription: 'Pure linen camp collar top', tags: 'top,linen,summer,relaxed,beach', gender: 'WOMEN', basePrice: 1799, salePrice: 1299, sku: 'W-TP-805', categorySlug: 'women-tops', brandSlug: 'classic-threads', fabric: 'Linen', material: '100% Linen', washCare: 'Hand wash or gentle machine wash. Hang dry.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: true, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, BEIGE, BLUE], imageCount: 7 },
  { name: 'Sequin Party Top', description: 'Show-stopping sequin top with full sequin embellishment on the front panel. Features a round neckline, long sleeves, and a back zip closure. The fully lined interior ensures comfort against the skin. Perfect for New Year\'s Eve, birthday parties, and festive celebrations.', shortDescription: 'Full sequin party top', tags: 'top,sequin,party,glamorous,celebration', gender: 'WOMEN', basePrice: 2499, salePrice: 1799, sku: 'W-TP-806', categorySlug: 'women-tops', brandSlug: 'elite-collection', fabric: 'Sequin Mesh', material: 'Polyester with Sequin Embellishment', washCare: 'Hand wash cold only. Do not wring or twist.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: true, sizes: WOMEN_SIZES, colors: [BLACK, GOLD, SILVER], imageCount: 7 },
  { name: 'Knit V-Neck Sweater Top', description: 'Cozy knit sweater top with a V-neckline and relaxed fit. Made from soft acrylic-cotton blend with a chunky knit texture. Features ribbed trims and a slightly cropped length. A transitional piece that bridges summer and winter wardrobes.', shortDescription: 'Chunky knit V-neck sweater', tags: 'top,sweater,knit,v-neck,winter,cozy', gender: 'WOMEN', basePrice: 1999, salePrice: 1399, sku: 'W-TP-807', categorySlug: 'women-tops', brandSlug: 'urban-style', fabric: 'Acrylic Cotton Blend', material: '60% Acrylic, 40% Cotton', washCare: 'Hand wash cold. Lay flat to dry.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [GREY, BEIGE, NAVY, PINK], imageCount: 7 },

  // ==================== WOMEN - SAREES (5) ====================
  { name: 'Banarasi Silk Saree', description: 'Exquisite Banarasi silk saree with intricate gold zari weaving throughout the body and a lavish pallu. Comes with a matching blouse piece. The rich silk drapes beautifully creating an unmistakable aura of tradition and luxury. Perfect for weddings and grand celebrations.', shortDescription: 'Gold zari Banarasi silk saree', tags: 'saree,silk,banarasi,wedding,luxury,gold', gender: 'WOMEN', basePrice: 8999, salePrice: 6499, sku: 'W-SR-901', categorySlug: 'women-sarees', brandSlug: 'premium-wear', fabric: 'Banarasi Silk', material: '100% Pure Silk with Gold Zari', washCare: 'Dry clean only. Store folded in muslin cloth.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: true, sizes: ['FREE SIZE'], colors: [MAROON, GREEN, NAVY], imageCount: 8 },
  { name: 'Chiffon Printed Saree', description: 'Lightweight chiffon saree with digital floral print. Easy to drape with a natural fall that flatters all body types. Comes with a matching running blouse material. The sheer chiffon creates an elegant, flowing silhouette.', shortDescription: 'Printed chiffon saree with blouse', tags: 'saree,chiffon,printed,floral,lightweight', gender: 'WOMEN', basePrice: 2999, salePrice: 1999, sku: 'W-SR-902', categorySlug: 'women-sarees', brandSlug: 'urban-style', fabric: 'Chiffon', material: '100% Georgette Chiffon', washCare: 'Hand wash cold. Do not wring. Dry in shade.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: ['FREE SIZE'], colors: [BLUE, PINK, GREEN], imageCount: 7 },
  { name: 'Cotton Handloom Saree', description: 'Authentic handloom cotton saree with traditional temple border and pallu motifs. Made from hand-spun, hand-woven cotton that is breathable and comfortable for all-day wear. The natural texture and slight irregularities celebrate the artisan\'s craft.', shortDescription: 'Handloom cotton with temple border', tags: 'saree,cotton,handloom,traditional,artisan', gender: 'WOMEN', basePrice: 3499, salePrice: 2499, sku: 'W-SR-903', categorySlug: 'women-sarees', brandSlug: 'classic-threads', fabric: 'Handloom Cotton', material: '100% Hand-spun Hand-woven Cotton', washCare: 'Hand wash cold first 3 washes. Machine wash gentle after.', isFeatured: true, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: ['FREE SIZE'], colors: [WHITE, BLUE, YELLOW], imageCount: 7 },
  { name: 'Satin Party Saree', description: 'Glamorous satin saree with a lustrous finish that catches light beautifully. Features a sequin-embellished border and pallu. Comes with a heavily embellished blouse piece. The smooth satin drapes like liquid gold for a red-carpet-worthy look.', shortDescription: 'Sequin border satin saree', tags: 'saree,satin,party,glamorous,sequin', gender: 'WOMEN', basePrice: 5999, salePrice: 4199, sku: 'W-SR-904', categorySlug: 'women-sarees', brandSlug: 'elite-collection', fabric: 'Satin', material: '100% Poly Satin with Sequin', washCare: 'Dry clean only.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: ['FREE SIZE'], colors: [BLACK, GREEN, MAROON], imageCount: 7 },
  { name: 'Organza Tissue Saree', description: 'Ethereal organza tissue saree with a shimmering metallic sheen. Features a delicate scalloped border with pearl detailing. The stiff yet lightweight organza creates structured drapes that hold their shape beautifully. Comes with a matching blouse piece.', shortDescription: 'Metallic organza tissue saree', tags: 'saree,organza,tissue,metallic,elegant', gender: 'WOMEN', basePrice: 7499, salePrice: 5499, sku: 'W-SR-905', categorySlug: 'women-sarees', brandSlug: 'elite-collection', fabric: 'Organza Tissue', material: 'Organza with Metallic Tissue', washCare: 'Dry clean only. Handle with care.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: ['FREE SIZE'], colors: [GOLD, SILVER, PINK], imageCount: 7 },

  // ==================== KIDS (8) ====================
  { name: 'Printed Cotton T-Shirt Set (3-Pack)', description: 'Value pack of three cotton t-shirts in fun prints. Made from soft, breathable cotton that is gentle on kids\' skin. Pre-shrunk fabric with reinforced seams to withstand active play. Bright colors and playful prints that kids love.', shortDescription: '3-pack printed cotton tees', tags: 'kids,t-shirt,set,cotton,printed,value-pack', gender: 'KIDS', basePrice: 1299, salePrice: 899, sku: 'K-TS-001', categorySlug: 'kids-t-shirts', brandSlug: 'premium-wear', fabric: 'Cotton', material: '100% Cotton 160 GSM', washCare: 'Machine wash cold. Tumble dry low.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: KID_SIZES, colors: [BLUE, RED, GREEN], imageCount: 7 },
  { name: 'Denim Overalls', description: 'Adorable denim overalls with adjustable straps and snap-button closures. Features a front bib pocket and side pockets. Made from soft stretch denim that moves with active kids. The classic overalls silhouette never goes out of style.', shortDescription: 'Stretch denim kids overalls', tags: 'kids,overalls,denim,classic,cute', gender: 'KIDS', basePrice: 1799, salePrice: 1299, sku: 'K-JN-001', categorySlug: 'kids-jeans', brandSlug: 'urban-style', fabric: 'Stretch Denim', material: '98% Cotton, 2% Elastane', washCare: 'Machine wash cold inside out.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: KID_SIZES, colors: [BLUE, BLACK], imageCount: 7 },
  { name: 'Princess Party Dress', description: 'Enchanting princess dress with a tulle skirt and satin bodice. Features a V-neckline with delicate lace trim, a concealed back zip, and a built-in petticoat for volume. The magical twirl-worthy skirt makes every little girl feel like royalty.', shortDescription: 'Tulle princess party dress', tags: 'kids,dress,princess,party,tulle,glamorous', gender: 'KIDS', basePrice: 2499, salePrice: 1799, sku: 'K-DR-001', categorySlug: 'kids-dresses', brandSlug: 'elite-collection', fabric: 'Tulle & Satin', material: '100% Polyester Tulle, Satin Lining', washCare: 'Hand wash cold. Hang dry. Do not wring tulle.', isFeatured: true, isNewArrival: true, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: KID_SIZES, colors: [PINK, WHITE, BLUE], imageCount: 7 },
  { name: 'Superhero Graphic Hoodie', description: 'Fun superhero-themed hoodie with a bold chest graphic and matching hood lining. Made from warm cotton fleece with a kangaroo pocket. The playful design sparks imagination while the comfortable fabric keeps little ones cozy.', shortDescription: 'Superhero graphic kids hoodie', tags: 'kids,hoodie,superhero,graphic,fun', gender: 'KIDS', basePrice: 1499, salePrice: 999, sku: 'K-HD-001', categorySlug: 'kids-t-shirts', brandSlug: 'street-vogue', fabric: 'Cotton Fleece', material: '80% Cotton, 20% Polyester', washCare: 'Machine wash cold. Tumble dry low.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: true, flashSale: false, festivalOffer: false, sizes: KID_SIZES, colors: [BLUE, RED, BLACK], imageCount: 7 },
  { name: 'Floral Summer Dress', description: 'Sweet floral print dress in lightweight cotton voile. Features a Peter Pan collar, short puff sleeves, and a gathered waist with a ribbon tie. The fully lined bodice and breathable fabric make it perfect for warm-weather adventures.', shortDescription: 'Cotton floral summer dress', tags: 'kids,dress,floral,summer,cotton,sweet', gender: 'KIDS', basePrice: 1699, salePrice: 1199, sku: 'K-DR-002', categorySlug: 'kids-dresses', brandSlug: 'classic-threads', fabric: 'Cotton Voile', material: '100% Cotton', washCare: 'Machine wash cold on gentle cycle.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: KID_SIZES, colors: [PINK, YELLOW, BLUE], imageCount: 7 },
  { name: 'Cargo Jogger Pants', description: 'Durable cargo jogger pants with elastic waistband and adjustable cuffs. Features side cargo pockets and reinforced knees for active play. Made from tough cotton twill that withstands rough and tumble adventures.', shortDescription: 'Durable cargo joggers for kids', tags: 'kids,jogger,cargo,pants,durable,active', gender: 'KIDS', basePrice: 1299, salePrice: 899, sku: 'K-TR-001', categorySlug: 'kids-trousers', brandSlug: 'urban-style', fabric: 'Cotton Twill', material: '100% Cotton', washCare: 'Machine wash cold. Tumble dry low.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: true, festivalOffer: false, sizes: KID_SIZES, colors: [GREEN, BLACK, BEIGE], imageCount: 7 },
  { name: 'Traditional Kurta Pyjama Set', description: 'Handsome traditional kurta pyjama set for boys. Features a woven jacquard kurta with mandarin collar and side slits, paired with comfortable elastic-waist pyjama pants. Perfect for festivals, weddings, and cultural celebrations.', shortDescription: 'Jacquard kurta pyjama set', tags: 'kids,kurta,pyjama,traditional,festive', gender: 'KIDS', basePrice: 1999, salePrice: 1499, sku: 'K-TR-001', categorySlug: 'kids-traditional', brandSlug: 'premium-wear', fabric: 'Cotton Jacquard', material: '100% Cotton', washCare: 'Hand wash cold. Dry in shade.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: true, sizes: KID_SIZES, colors: [NAVY, WHITE, MAROON], imageCount: 7 },
  { name: 'Winter Fleece Jacket', description: 'Warm fleece jacket with a full-zip front and stand collar. Made from anti-pill fleece that stays soft wash after wash. Features elasticated cuffs and zippered side pockets. A cozy layer for chilly mornings and outdoor play.', shortDescription: 'Anti-pill fleece winter jacket', tags: 'kids,jacket,fleece,winter,warm', gender: 'KIDS', basePrice: 1799, salePrice: 1299, sku: 'K-JK-001', categorySlug: 'kids-t-shirts', brandSlug: 'elite-collection', fabric: 'Anti-Pill Fleece', material: '100% Polyester Fleece', washCare: 'Machine wash cold. Tumble dry low.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: KID_SIZES, colors: [BLUE, RED, GREEN], imageCount: 7 },

  // ==================== ACCESSORIES (8) ====================
  { name: 'Leather Messenger Bag', description: 'Handcrafted full-grain leather messenger bag with an adjustable shoulder strap. Features a flap closure with brass buckle, padded laptop compartment (fits 15"), and multiple organizer pockets. Ages beautifully with a rich patina over time.', shortDescription: 'Full-grain leather messenger bag', tags: 'bag,messenger,leather,premium,laptop', gender: 'ACCESSORIES', basePrice: 5999, salePrice: 4199, sku: 'A-BG-001', categorySlug: 'accessories-bags', brandSlug: 'elite-collection', fabric: 'Full-Grain Leather', material: '100% Vegetable-Tanned Leather', washCare: 'Wipe with damp cloth. Condition leather periodically.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: ['ONE SIZE'], colors: [BLACK, BROWN, TAN], imageCount: 7 },
  { name: 'Canvas Backpack - Adventure Edition', description: 'Rugged canvas backpack designed for everyday adventures. Features a padded laptop sleeve, water bottle pockets, and a padded back panel with airflow channels. The roll-top closure allows adjustable capacity while the waxed canvas provides water resistance.', shortDescription: 'Waxed canvas adventure backpack', tags: 'bag,backpack,canvas,adventure,travel', gender: 'ACCESSORIES', basePrice: 3499, salePrice: 2499, sku: 'A-BG-002', categorySlug: 'accessories-bags', brandSlug: 'street-vogue', fabric: 'Waxed Canvas', material: '100% Waxed Cotton Canvas', washCare: 'Spot clean with damp cloth. Re-wax annually.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: ['ONE SIZE'], colors: [GREEN, NAVY, BLACK], imageCount: 7 },
  { name: 'Classic Leather Belt', description: 'Timeless leather belt with a brushed nickel buckle. Made from top-grain leather with a smooth finish. The 1.5" width is versatile enough for both formal trousers and casual jeans. A foundational accessory for any wardrobe.', shortDescription: 'Top-grain leather dress belt', tags: 'belt,leather,classic,formal,essential', gender: 'ACCESSORIES', basePrice: 1499, salePrice: 999, sku: 'A-BL-001', categorySlug: 'accessories-belts', brandSlug: 'classic-threads', fabric: 'Top-Grain Leather', material: '100% Leather with Nickel Buckle', washCare: 'Wipe clean. Avoid prolonged water exposure.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: ['28', '30', '32', '34', '36', '38', '40'], colors: [BLACK, BROWN], imageCount: 7 },
  { name: 'Aviator Sunglasses', description: 'Classic aviator sunglasses with polarized lenses and UV400 protection. Features a lightweight metal frame with adjustable nose pads for a comfortable fit. The iconic teardrop shape complements most face shapes while providing 100% UV protection.', shortDescription: 'Polarized aviator sunglasses', tags: 'sunglasses,aviator,polarized,uv-protection,classic', gender: 'ACCESSORIES', basePrice: 2499, salePrice: 1699, sku: 'A-SG-001', categorySlug: 'accessories-sunglasses', brandSlug: 'elite-collection', fabric: 'Metal Frame', material: 'Stainless Steel Frame, Polarized CR-39 Lens', washCare: 'Clean with included microfiber cloth.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: ['ONE SIZE'], colors: [BLACK, GOLD, SILVER], imageCount: 7 },
  { name: 'Minimalist Analog Watch', description: 'Sleek minimalist watch with a clean dial and genuine leather strap. Japanese quartz movement ensures reliable timekeeping. Water-resistant to 30 meters. The ultra-thin case profile (7mm) slides easily under shirt cuffs.', shortDescription: 'Minimalist Japanese quartz watch', tags: 'watch,analog,minimalist,leather,premium', gender: 'ACCESSORIES', basePrice: 4999, salePrice: 3499, sku: 'A-WT-001', categorySlug: 'accessories-watches', brandSlug: 'modern-fit', fabric: 'Stainless Steel', material: '316L Stainless Steel, Sapphire Crystal, Leather Strap', washCare: 'Avoid water contact. Clean with soft cloth.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: ['ONE SIZE'], colors: [BLACK, BROWN, NAVY], imageCount: 8 },
  { name: 'Suede Chelsea Boots', description: 'Refined Chelsea boots in premium suede with elastic side panels for easy on/off. Features a leather sole with rubber heel grip and Goodyear welt construction. A versatile boot that pairs equally well with suits and denim.', shortDescription: 'Premium suede Chelsea boots', tags: 'boots,chelsea,suede,premium,formal', gender: 'ACCESSORIES', basePrice: 6999, salePrice: 4999, sku: 'A-FT-001', categorySlug: 'footwear-boots', brandSlug: 'elite-collection', fabric: 'Suede', material: '100% Suede Upper, Leather Sole', washCare: 'Apply suede protector spray. Brush regularly.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: SHOE_SIZES, colors: [BLACK, BROWN, TAN], imageCount: 7 },
  { name: 'Canvas Tote Bag', description: 'Oversized canvas tote bag with reinforced handles and a magnetic snap closure. Features an interior zip pocket and two slip pockets. The structured base allows it to stand upright. A practical everyday bag that only gets better with age.', shortDescription: 'Structured canvas tote bag', tags: 'bag,tote,canvas,everyday,practical', gender: 'ACCESSORIES', basePrice: 1999, salePrice: 1399, sku: 'A-BG-003', categorySlug: 'accessories-bags', brandSlug: 'urban-style', fabric: 'Canvas', material: '100% Heavyweight Cotton Canvas', washCare: 'Machine wash cold. Hang dry.', isFeatured: false, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: true, festivalOffer: false, sizes: ['ONE SIZE'], colors: [BEIGE, BLACK, NAVY], imageCount: 7 },
  { name: 'Wool Scarf', description: 'Luxuriously soft wool scarf with a herringbone weave pattern. Made from 100% merino wool that provides exceptional warmth without itchiness. The generous size (70" x 12") allows multiple styling options. A winter essential.', shortDescription: 'Merino wool herringbone scarf', tags: 'scarf,wool,merino,winter,warmth', gender: 'ACCESSORIES', basePrice: 1999, salePrice: 1399, sku: 'A-SC-001', categorySlug: 'accessories-scarves', brandSlug: 'premium-wear', fabric: 'Merino Wool', material: '100% Merino Wool', washCare: 'Hand wash cold in wool detergent. Lay flat to dry.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: ['ONE SIZE'], colors: [GREY, NAVY, BEIGE, BLACK], imageCount: 7 },

  // ==================== FOOTWEAR (8) ====================
  { name: 'Classic White Sneakers', description: 'Timeless white leather sneakers with a clean minimalist design. Features a cushioned insole for all-day comfort, durable rubber outsole, and reinforced stitching. The versatile white sneaker is the foundation of any modern wardrobe.', shortDescription: 'Minimalist white leather sneakers', tags: 'sneakers,white,leather,classic,minimalist', gender: 'MEN', basePrice: 3999, salePrice: 2799, sku: 'M-FT-001', categorySlug: 'footwear-sneakers', brandSlug: 'modern-fit', fabric: 'Leather', material: '100% Leather Upper, Rubber Sole', washCare: 'Wipe with damp cloth. Use leather protector.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: SHOE_SIZES, colors: [WHITE, BLACK], imageCount: 7 },
  { name: 'Running Performance Shoes', description: 'Engineered for high-performance running with responsive foam cushioning and a breathable mesh upper. Features a reinforced heel counter for stability and a flex groove outsole for natural foot movement. Built for speed and comfort.', shortDescription: 'Performance running shoes', tags: 'shoes,running,performance,sports,athletic', gender: 'MEN', basePrice: 5999, salePrice: 4199, sku: 'M-FT-002', categorySlug: 'footwear-sports-shoes', brandSlug: 'elite-collection', fabric: 'Mesh', material: 'Engineered Mesh, EVA Midsole, Rubber Outsole', washCare: 'Hand wash with mild soap. Air dry away from direct heat.', isFeatured: true, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: SHOE_SIZES, colors: [BLACK, BLUE, RED], imageCount: 7 },
  { name: 'Suede Loafers', description: 'Elegant suede loafers with hand-stitched apron toe. Features a cushioned footbed and a flexible leather outsole. The penny loafer design is a preppy classic that transitions seamlessly from casual to semi-formal settings.', shortDescription: 'Suede penny loafers', tags: 'loafers,suede,formal,classic,preppy', gender: 'MEN', basePrice: 4499, salePrice: 3199, sku: 'M-FT-003', categorySlug: 'footwear-formal-shoes', brandSlug: 'classic-threads', fabric: 'Suede', material: 'Suede Upper, Leather Sole', washCare: 'Apply suede protector. Brush with suede brush.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: false, flashSale: false, festivalOffer: false, sizes: SHOE_SIZES, colors: [TAN, BROWN, BLACK], imageCount: 7 },
  { name: 'Platform Chunky Sneakers', description: 'Statement chunky sneakers with an exaggerated platform sole. Features a mixed-material upper combining leather, mesh, and synthetic overlays. The thick sole adds 3 inches of height while the cushioned insole ensures comfort.', shortDescription: 'Platform chunky sneakers', tags: 'sneakers,chunky,platform,statement,trendy', gender: 'WOMEN', basePrice: 4999, salePrice: 3499, sku: 'W-FT-001', categorySlug: 'footwear-sneakers', brandSlug: 'street-vogue', fabric: 'Mixed Materials', material: 'Leather, Mesh, Synthetic', washCare: 'Wipe clean with damp cloth.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [WHITE, BLACK, PINK], imageCount: 7 },
  { name: 'Kolhapuri Chappals', description: 'Handcrafted Kolhapuri chappals in genuine leather with traditional braided strap design. Made by skilled artisans using age-old techniques. The vegetable-tanned leather insole molds to your foot shape over time for a custom fit.', shortDescription: 'Handcrafted leather Kolhapuri chappals', tags: 'chappals,kolhapuri,leather,handmade,traditional', gender: 'WOMEN', basePrice: 1999, salePrice: 1499, sku: 'W-FT-002', categorySlug: 'footwear-sandals', brandSlug: 'classic-threads', fabric: 'Leather', material: '100% Vegetable-Tanned Leather', washCare: 'Avoid water. Clean with leather conditioner.', isFeatured: true, isNewArrival: false, isBestSeller: true, isTrending: false, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BROWN, TAN], imageCount: 7 },
  { name: 'Sport Running Shoes', description: 'Lightweight sport running shoes with responsive ZoomAir cushioning. Features a breathable flyknit upper and a carbon rubber outsole with multi-directional traction patterns. Designed for both track and road running.', shortDescription: 'Lightweight sport running shoes', tags: 'shoes,sport,running,lightweight,performance', gender: 'MEN', basePrice: 6499, salePrice: 4499, sku: 'M-FT-004', categorySlug: 'footwear-sports-shoes', brandSlug: 'premium-wear', fabric: 'Flyknit', material: 'Flyknit Upper, ZoomAir Unit, Carbon Rubber Outsole', washCare: 'Hand wash in cold water. Air dry.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: false, flashSale: true, festivalOffer: false, sizes: SHOE_SIZES, colors: [BLACK, GREY, BLUE], imageCount: 7 },
  { name: 'Woven Leather Sandals', description: 'Artisanal woven leather sandals with a comfortable flat sole. Hand-woven genuine leather straps create an intricate basket-weave pattern. The adjustable ankle strap ensures a secure fit. Perfect for summer outings.', shortDescription: 'Hand-woven leather flat sandals', tags: 'sandals,leather,woven,summer,artisan', gender: 'WOMEN', basePrice: 2499, salePrice: 1799, sku: 'W-FT-003', categorySlug: 'footwear-sandals', brandSlug: 'premium-wear', fabric: 'Leather', material: '100% Hand-woven Leather', washCare: 'Wipe with damp cloth. Condition leather.', isFeatured: false, isNewArrival: false, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [TAN, BLACK, BROWN], imageCount: 7 },
  { name: 'Platform Combat Boots', description: 'Edgy platform combat boots with a chunky lug sole. Features a lace-up front with metal eyelets, a padded collar for comfort, and a pull tab at the heel. The platform adds height while the combat style adds attitude.', shortDescription: 'Chunky platform combat boots', tags: 'boots,combat,platform,edgy,statement', gender: 'WOMEN', basePrice: 4999, salePrice: 3499, sku: 'W-FT-004', categorySlug: 'footwear-boots', brandSlug: 'street-vogue', fabric: 'Faux Leather', material: 'Faux Leather Upper, Rubber Sole', washCare: 'Wipe with damp cloth. Apply water repellent spray.', isFeatured: false, isNewArrival: true, isBestSeller: false, isTrending: true, flashSale: false, festivalOffer: false, sizes: WOMEN_SIZES, colors: [BLACK, BROWN], imageCount: 7 },
];

const MULTI = { name: 'Multi', hex: '#ff6b35' };
const LAVENDER = { name: 'Lavender', hex: '#c084fc' };
const OLIVE = { name: 'Olive', hex: '#65a30d' };
const BROWN = { name: 'Brown', hex: '#92400e' };
const TAN = { name: 'Tan', hex: '#d2a679' };
const GOLD = { name: 'Gold', hex: '#d4a853' };
const SILVER = { name: 'Silver', hex: '#c0c0c0' };
const YELLOW = { name: 'Yellow', hex: '#eab308' };
const DARK_BLUE = { name: 'Dark Blue', hex: '#1e3a5f' };
const DARK_GREY = { name: 'Dark Grey', hex: '#374151' };
const LIGHT_BLUE = { name: 'Light Blue', hex: '#93c5fd' };

async function main() {
  console.log('Starting seed of 100 products...');

  // Ensure categories exist
  const menSubs = ['Shirts', 'T-Shirts', 'Jeans', 'Trousers', 'Jackets', 'Hoodies', 'Kurtas', 'Blazers', 'Shorts'];
  const womenSubs = ['Sarees', 'Kurtis', 'Dresses', 'Tops', 'T-Shirts', 'Jeans', 'Leggings', 'Palazzo', 'Skirts', 'Jackets', 'Nightwear'];
  const kidsSubs = ['T-Shirts', 'Shirts', 'Jeans', 'Dresses', 'Trousers', 'Activewear', 'Traditional', 'Nightwear'];
  const accSubs = ['Bags', 'Belts', 'Watches', 'Sunglasses', 'Hats', 'Scarves', 'Jewellery', 'Wallets'];
  const footwearSubs = ['Sneakers', 'Formal Shoes', 'Sandals', 'Slippers', 'Sports Shoes', 'Boots', 'Flats'];

  const menCat = await prisma.category.upsert({ where: { slug: 'men' }, update: {}, create: { name: 'Men', slug: 'men', gender: 'MEN', displayOrder: 1 } });
  const womenCat = await prisma.category.upsert({ where: { slug: 'women' }, update: {}, create: { name: 'Women', slug: 'women', gender: 'WOMEN', displayOrder: 2 } });
  const kidsCat = await prisma.category.upsert({ where: { slug: 'kids' }, update: {}, create: { name: 'Kids', slug: 'kids', gender: 'KIDS', displayOrder: 3 } });
  const accCat = await prisma.category.upsert({ where: { slug: 'accessories' }, update: {}, create: { name: 'Accessories', slug: 'accessories', gender: 'ACCESSORIES', displayOrder: 4 } });
  const footwearCat = await prisma.category.upsert({ where: { slug: 'footwear' }, update: {}, create: { name: 'Footwear', slug: 'footwear', gender: 'ACCESSORIES', displayOrder: 6 } });

  for (const name of menSubs) {
    await prisma.category.upsert({ where: { slug: `men-${name.toLowerCase().replace(/\s+/g, '-')}` }, update: {}, create: { name, slug: `men-${name.toLowerCase().replace(/\s+/g, '-')}`, parentId: menCat.id, gender: 'MEN' } });
  }
  for (const name of womenSubs) {
    await prisma.category.upsert({ where: { slug: `women-${name.toLowerCase().replace(/\s+/g, '-')}` }, update: {}, create: { name, slug: `women-${name.toLowerCase().replace(/\s+/g, '-')}`, parentId: womenCat.id, gender: 'WOMEN' } });
  }
  for (const name of kidsSubs) {
    await prisma.category.upsert({ where: { slug: `kids-${name.toLowerCase().replace(/\s+/g, '-')}` }, update: {}, create: { name, slug: `kids-${name.toLowerCase().replace(/\s+/g, '-')}`, parentId: kidsCat.id, gender: 'KIDS' } });
  }
  for (const name of accSubs) {
    await prisma.category.upsert({ where: { slug: `accessories-${name.toLowerCase().replace(/\s+/g, '-')}` }, update: {}, create: { name, slug: `accessories-${name.toLowerCase().replace(/\s+/g, '-')}`, parentId: accCat.id, gender: 'ACCESSORIES' } });
  }
  for (const name of footwearSubs) {
    await prisma.category.upsert({ where: { slug: `footwear-${name.toLowerCase().replace(/\s+/g, '-')}` }, update: {}, create: { name, slug: `footwear-${name.toLowerCase().replace(/\s+/g, '-')}`, parentId: footwearCat.id, gender: 'ACCESSORIES' } });
  }

  // Ensure brands exist
  const brandNames = ['Premium Wear', 'Urban Style', 'Classic Threads', 'Modern Fit', 'Elite Collection', 'Street Vogue'];
  for (const name of brandNames) {
    await prisma.brand.upsert({ where: { slug: name.toLowerCase().replace(/\s+/g, '-') }, update: {}, create: { name, slug: name.toLowerCase().replace(/\s+/g, '-'), isActive: true } });
  }

  const brands = await prisma.brand.findMany();
  const brandMap: Record<string, string> = {};
  for (const b of brands) brandMap[b.slug] = b.id;

  const categories = await prisma.category.findMany();
  const catMap: Record<string, string> = {};
  for (const c of categories) catMap[c.slug] = c.id;

  let created = 0;
  let skipped = 0;

  for (const p of products) {
    const catId = catMap[p.categorySlug];
    if (!catId) {
      console.log(`  SKIP: Category "${p.categorySlug}" not found for "${p.name}"`);
      skipped++;
      continue;
    }

    const brandId = brandMap[p.brandSlug] || null;
    const slug = p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + p.sku.toLowerCase();
    const discountPercent = p.salePrice ? Math.round(((p.basePrice - p.salePrice) / p.basePrice) * 100) : null;

    const existing = await prisma.product.findUnique({ where: { sku: p.sku } });
    if (existing) {
      // Update images if product exists but has fewer than p.imageCount images
      const imgCount = await prisma.productImage.count({ where: { productId: existing.id } });
      if (imgCount < p.imageCount) {
        await prisma.productImage.deleteMany({ where: { productId: existing.id } });
        await prisma.productImage.createMany({
          data: imgs(p.sku.toLowerCase(), p.imageCount).map((img) => ({ ...img, productId: existing.id })),
        });
        console.log(`  UPDATED images for "${p.name}" (${p.imageCount} images)`);
      }
      skipped++;
      continue;
    }

    const product = await prisma.product.create({
      data: {
        name: p.name,
        slug,
        description: p.description,
        shortDescription: p.shortDescription,
        tags: p.tags,
        status: 'PUBLISHED',
        categoryId: catId,
        brandId,
        gender: p.gender,
        basePrice: p.basePrice,
        salePrice: p.salePrice,
        discountPercent,
        currency: 'INR',
        sku: p.sku,
        isActive: true,
        isFeatured: p.isFeatured,
        isNewArrival: p.isNewArrival,
        isBestSeller: p.isBestSeller,
        isTrending: p.isTrending,
        fabric: p.fabric,
        material: p.material,
        washCare: p.washCare,
        hsnCode: '6109',
        gstRate: 12,
        returnAvailable: true,
        returnPeriod: 30,
        exchangeAvailable: true,
        warrantyPeriod: 'Standard Quality',
        couponEligible: true,
        flashSale: p.flashSale,
        bogo: false,
        festivalOffer: p.festivalOffer,
        metaTitle: p.name,
        metaDescription: p.shortDescription,
        metaKeywords: p.tags,
        publishedAt: new Date(),
      },
    });

    // Images
    await prisma.productImage.createMany({
      data: imgs(p.sku.toLowerCase(), p.imageCount).map((img) => ({ ...img, productId: product.id })),
    });

    // Variants
    const variantData = variants(p.sku, p.sizes, p.colors, p.salePrice);
    await prisma.productVariant.createMany({
      data: variantData.map((v) => ({ ...v, productId: product.id })),
    });

    created++;
    if (created % 10 === 0) console.log(`  Created ${created} products...`);
  }

  console.log(`\nDone! Created: ${created}, Skipped (existing): ${skipped}`);

  const totalCount = await prisma.product.count();
  const totalImages = await prisma.productImage.count();
  const totalVariants = await prisma.productVariant.count();
  console.log(`Total products in DB: ${totalCount}`);
  console.log(`Total images in DB: ${totalImages}`);
  console.log(`Total variants in DB: ${totalVariants}`);
}

main()
  .catch((e) => {
    console.error('SEED FAILED:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
